### ISSUE TITLE
mi window curtain

### ISSUE THREAD

**Issue by dly2345** [hassio-addons/repository#10]
[HomeAssistant] 'cover.curtain_158d00016c02e5' is a cover but does not have a 'homebridge_cover_type' property set. You must set it to either 'rollershutter' or 'garage_door' in the customize section of your Home Assistant configuration. It will not be available to Homebridge until you do.

**Comment by frenck** [comment]
I'm not sure what you are asking, reporting or telling me with this?

If this is an issue you've encountered; the answer is in the error message already.

**Comment by frenck** [comment]
Closing this issue.
