### ISSUE TITLE
❇ Facebox

### ISSUE THREAD

**Issue by silfa718** [hassio-addons/repository#101]
Would anyone consider making an addon for the facebox component?

https://www.home-assistant.io/components/image_processing.facebox/

<blockquote><img src="https://www.home-assistant.io/images/default-social.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/components/image_processing.facebox/">Facebox</a></strong></div><div>Detect and recognize faces with Facebox.</div></blockquote>

**Comment by jamesb2147** [comment]
I don't quite have my setup working yet, but it is in progress. My only issue right now, I think, is getting my options.json file to load so I can pass the MB_KEY in and parse that into a local environment variable.

**Comment by ikrowni** [comment]
This would be awesome if we got it as an addon.

**Comment by tortfeaser** [comment]
Now with the Raspberry 4, processing grunt is less of an issue.

**Comment by gregoryduckworth** [comment]
Would love this to be done!

**Comment by tjorim** [comment]
Although it's nice software, it's difficult to pour into an add-on as there is no source code available.

**Comment by pattyland** [comment]
With the Portainer add-on you can have Facebox up and running under Home Assistant (HassOS) in 3 minutes
