### ISSUE TITLE
❇ phpMyAdmin for MYSQL access

### ISSUE THREAD

**Issue by mzac** [hassio-addons/repository#103]
# Problem/Motivation

Addon needed for managing mysql database.  We had discussed this briefly on Twitter but I never made an official request.  I'd like to do it myself but I don't have the time or know how on how to create the addon
https://www.phpmyadmin.net/

## Expected behavior

Be able to monitor, modify, access mysql database in Home Assistant

## Actual behavior

Right now the only way is with an external client

## Steps to reproduce

None

## Proposed changes

Create an addon for phpMyAdmin
https://www.phpmyadmin.net/

<blockquote><img src="https://www.phpmyadmin.net/static/images/logo-og.png" width="48" align="right"><div><img src="/static/favicon.ico" height="14"> phpMyAdmin</div><div><strong><a href="https://www.phpmyadmin.net/">phpMyAdmin</a></strong></div></blockquote>
<blockquote><img src="https://www.phpmyadmin.net/static/images/logo-og.png" width="48" align="right"><div><img src="/static/favicon.ico" height="14"> phpMyAdmin</div><div><strong><a href="https://www.phpmyadmin.net/">phpMyAdmin</a></strong></div></blockquote>

**Comment by Smitty357** [comment]
This would be a great addition. I am currently looking for options myself, but do not have a system available to run it from. It would be nice to have it running on my Pi where my MariaDB is running.

**Comment by roblandry** [comment]
This would be a good starting point: https://github.com/JackGruber/docker_phpmyadmin

If i knew how to create an addon, id do it! I am playing with it trying to find something that makes it work, however at the moment it is manually installed via docker and working well.

**Comment by frenck** [comment]
:tada: <https://github.com/hassio-addons/addon-phpmyadmin>
