### ISSUE TITLE
SSL Reverse Proxy Generator with NGINX

### ISSUE THREAD

**Issue by timmo001** [hassio-addons/repository#104]
# Problem/Motivation

There are some apps in my network or what addons like motionEye create with camera feeds with basic auth but no SSL.

A way to generate an array/list of nginx config files via an addon which acts as a reverse proxy to these apps would be great. It would also allow me to not have to copy certificates every time they update to other servers and instead keep them all in one place.

## Proposed changes

- Create an addon which creates nginx files on startup via an array of urls / ports
- Run the server under specified ports from the config on the `host_network`

**Comment by frenck** [comment]
Not an option in the way Hassio uses Docker closing this issue for now.
