### ISSUE TITLE
❇AdGuard Home

### ISSUE THREAD

**Issue by noorbertt** [hassio-addons/repository#105]
There is a way add https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi to hassio add-ons? Like pihole add-on.

<blockquote><img src="https://avatars1.githubusercontent.com/u/8361145?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/AdguardTeam/AdGuardHome">AdguardTeam/AdGuardHome</a></strong></div><div>Network-wide ads & trackers blocking DNS server. Contribute to AdguardTeam/AdGuardHome development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
Reference to the issue @ AdGuard: AdguardTeam/AdGuardHome#379

Add-on development is almost done. Awaiting the next release, that solves a couple of issues that currently blocks a proper/clean add-on.

**Comment by frenck** [comment]
Released!

https://github.com/hassio-addons/addon-adguard-home

Thanks for the suggestion @noorbertt 👍
