### ISSUE TITLE
❇ Toon Secure Control

### ISSUE THREAD

**Issue by RudolfRendier** [hassio-addons/repository#106]
# Problem/Motivation
Rooted Toons (Quby's/Eneco's Smart Thermostat) allow remote control via web.
@jonkootje Turned this http-api into a neat GUI that resembles the real Toon app.
It works rather nicely and allows anyone in your household to control the thermostat without installing an app first.

Here's the original source code:
https://github.com/jonkootje/secure-toon-control
Here's a useful fork containing a bug-fix:
https://github.com/sanderdh/secure-toon-control
Here's my fork containing hass.io-variables wrapped in %%:
https://github.com/RudolfRendier/secure-toon-control

## Proposed changes
Here's a working hass.io-addon that was based on Pi-Hole:
https://github.com/RudolfRendier/addon-secure-toon-control

I left a lot of coffee-links intact, because it's based on the works of others. I don't feel like claiming it as my own.
Thanks @frenck for the great example.

<blockquote><img src="https://avatars1.githubusercontent.com/u/18559467?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/jonkootje/secure-toon-control">jonkootje/secure-toon-control</a></strong></div><div>Securely control your rooted toon thermostat from outside your local network. - jonkootje/secure-toon-control</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/14254442?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/sanderdh/secure-toon-control">sanderdh/secure-toon-control</a></strong></div><div>Securely control your rooted toon thermostat from outside your local network. - sanderdh/secure-toon-control</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/490658?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/RudolfRendier/secure-toon-control">RudolfRendier/secure-toon-control</a></strong></div><div>Securely control your rooted toon thermostat from outside your local network. - RudolfRendier/secure-toon-control</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/490658?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/RudolfRendier/addon-secure-toon-control">RudolfRendier/addon-secure-toon-control</a></strong></div><div>hass.io addon for Secure Toon Control. Contribute to RudolfRendier/addon-secure-toon-control development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
All linked projects are stalled, besides Home Assistant supports Toon natively.

So I'll go ahead and close this suggestion.

Nevertheless, thanks for providing it!
