### ISSUE TITLE
Where is a Konnected addon? Whos up for the task?

### ISSUE THREAD

**Issue by clintonmcc** [hassio-addons/repository#107]
# Problem/Motivation

> We need to get an Alarm system on here

## Expected behavior

> Hopefully someone will come to tak.

## Actual behavior

> Hoping it will happen

**Comment by clintonmcc** [comment]
konnected.io

**Comment by frenck** [comment]
As far as I know, Konnected does not need a server... So am confused now, what should this addon do or run?

Can you reference the software the addon should be running?

**Comment by clintonmcc** [comment]
Looking at a simple way of bringing up a sample setup,eg making a new konnected.yaml with data in it and being able to edit the names of the devices and saving that to the yaml file and add in the includes line into the configuration.yaml. Maybe a script them with a web interface to edit the konnected.yaml. Simplifying the setup.

**Comment by clintonmcc** [comment]
A configurator that will add a konnected.yaml file if not read whats there,then be able to edit from a gui.

**Comment by frenck** [comment]
That is not the purpose of addons.
Addons run services. You might be better of to request this on Home Assistant.


There are multiple addons out there to help you with the editing of files. Eg configurator or the IDE addon.

**Comment by clintonmcc** [comment]
Konnected has brilliant product. Its a security product and HAis a NON cloud dependent system. We dont want the Alarm system to be online. Smarthings has been the focus...but lets make it easier in HA

**Comment by frenck** [comment]
@clintonmcc I do agree, but based on your reactions and answers, I have to conclude you don't know the difference between add-ons and components.

Again add-ons run services (e.g., database server), Home Assistant components connect to systems and integrate. Just like Konnected, Home Assistant is a non-cloud dependent system.

You are barking against the wrong tree here.

**Comment by clintonmcc** [comment]
Could the Love lace migration tool add on not be adapted to create a konnected.yaml and fill it with the basic config? This can then be edited with a gui for customising?

**Comment by ludeeus** [comment]
That does not make sense, what you can do is opening a feature request on the forum to have the konnected component create a default configuration

**Comment by clintonmcc** [comment]
https://esphomelib.com/esphomeyaml/guides/getting_started_hassio.html
What about something like this for Konnecred?

**Comment by frenck** [comment]
@clintonmcc I think we made it pretty clear, this is not going to happen on our end.
