### ISSUE TITLE
❇ Wireguard

### ISSUE THREAD

**Issue by darookee** [hassio-addons/repository#108]
# Problem/Motivation

Even though there is an OpenVPN addon in development I think it would be good to also support Wireguard. There seems to be an [docker container](https://github.com/activeeos/wireguard-docker) for it already...

**Comment by fredrike** [comment]
There seem to be an addon already: [whiskerz007/addon-wireguard](https://github.com/whiskerz007/addon-wireguard)

**Comment by keatontaylor** [comment]
@fredrike, seems the link to the addon already created doesn't seem to build correctly for arm based devices.

**Comment by fredrike** [comment]
Same for x64 devices. Sorry for not testing first.

Might try to wrap my head around addons and create an addon for wireguard.

**Comment by martiabernathey** [comment]
I believe Frenck is testing one atm. If I remember correctly whiskers version was only for the Rpi.

**Comment by frenck** [comment]
I have already created an add-on for Wireguard, however, not released it yet. My main concern is a complexity concern for user. I'm still trying to find methods to make it easier in use.

Currently, it is able to switch automatically between kernel supported Wireguard and userspace version as a fallback and works with any Hass.io support architecture.

**Comment by frenck** [comment]
The add-on has been released: https://frenck.dev/introducing-wireguard-vpn-for-hass-io/
