### ISSUE TITLE
❇ Sonos-web

### ISSUE THREAD

**Issue by gieljnssns** [hassio-addons/repository#109]
https://github.com/Villarrealized/sonos-web

![image](https://user-images.githubusercontent.com/17234951/51442448-0f351d00-1cdd-11e9-9af8-3d75ed56cfb0.png)

# Problem/Motivation

>It would be nice to have panel for Sonos

Sonos Web is a browser based controller for your Sonos sound system.

Install Sonos Web on a single computer and access and manage your system from any browser on your network.

## Features
Sonos Web is a developing project and is not yet full-featured. Here are some of the currently available features:
 * Music Library
    * Search your entire music library with Top Results (Not available on official Sonos App)
    * Browse, Queue, & Play your entire music library by category
    * View Artists, Genres & Playlists with Album Art! (Not available on official Sonos App)
    * All artist & album names are links that take you to that item (very useful!)
 * Group rooms together via drag & drop
 * Queue management via icon on Now Playing bar
 * Party mode (Group all speakers into one group)
 * Quickly & easily switch between rooms/groups
 * Adjust individual speaker volume/mute or adjust for the whole group 
 * Play, pause, skip, and seek tracks
 * Shuffle & repeat controls 
 * Room selection from the Now Playing bar.

## Goals (Coming Soon)
 * Music Library
    * Sonos Playlists & Favorites
    * Other Music Services (ex. Pandora, Spotify, etc.) ...maybe? 
 * Recent Play History
 * Caching of searches and browsing for quicker load times

Maybe this helps. https://hub.docker.com/r/psychlist/docker-sonos-web-arm
https://github.com/pwt/docker-sonos-web-arm

**Comment by tjorim** [comment]
Looks a nice project! However, please note that the Spotify plugin is not yet available according to their documentation.

**Comment by gieljnssns** [comment]
Form me the most important is I can manage my queue...
If Spotify coms available it will be a nice surplus.
