### ISSUE TITLE
❇ HAProxy

### ISSUE THREAD

**Issue by adamotte** [hassio-addons/repository#111]
# Idea

There is no "routing" addon yet and i think it will be good to have one, especially with the increase in the number of addons and therefore the number of different ports used. 
We could then route each port on a specific path.
There seems to be an docker container for it already...

http://www.haproxy.org

**Comment by frenck** [comment]
We currently provide an NGinx Proxy Manager as a reverse proxy.

I have no plans on adding more add-ons that do the "same" thing.

Nevertheless, thanks for your suggestion.
