### ISSUE TITLE
❇ OwnTracks Recorder

### ISSUE THREAD

**Issue by tjorim** [hassio-addons/repository#112]
# Motivation
Now that Owntracks is converted to a nice integration, it would be cool to be able to see the history of tracked devices. OwnTracks itself already has a nice web app for this: https://github.com/owntracks/recorder. Owntracks recorder has an existing Docker image but that has mosquitto included. (We already have enough mqtt server add-ons I think.)

<blockquote><img src="https://avatars3.githubusercontent.com/u/6574523?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/owntracks/recorder">owntracks/recorder</a></strong></div><div>Store and access data published by OwnTracks apps. Contribute to owntracks/recorder development by creating an account on GitHub.</div></blockquote>

**Comment by chinachen008** [comment]
leave a comment
