### ISSUE TITLE
NUT is not shown

### ISSUE THREAD

**Issue by hmronline** [hassio-addons/repository#113]
# Problem/Motivation

Becase I would like to use the NUT Sensor Add-on

## Expected behavior

See NUT Sensor Add-on listed on available add-ons

## Actual behavior

It is not listed there... is missing.

## Steps to reproduce

Verify all available add-ons, you will realize NUT Sensor is not there.

## Proposed changes

Include it.
Thanks

**Comment by frenck** [comment]
Correct, this add-on has not been released.

**Comment by MichaelSchemmer** [comment]
Thanks for the reply.
Is there any timeline on a possible release of the add-on? I'd think that it would be helluva useful!
Thanks for all the work!

**Comment by frenck** [comment]
No, there is no timeline. This is an opensource project, based on peoples spare time they are willing to donate.
