### ISSUE TITLE
❇ Curve anomaly detection

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/repository#114]
# Problem/Motivation
Perform inspection of HA data in order to identify anomalies which we might want to create automated alerts for https://github.com/baidu/Curve

<blockquote><img src="https://avatars1.githubusercontent.com/u/13245940?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/baidu/Curve">baidu/Curve</a></strong></div><div>An Integrated Experimental Platform for time series data anomaly detection. - baidu/Curve</div></blockquote>

**Comment by josemotta** [comment]
Hi.
Have you seen Morgoth? Does it fit your reqs?

https://github.com/nathanielc/morgoth

**Comment by robmarkcole** [comment]
@josemotta thanks for the share, I'm not a user of InfluxDB so wasn't aware Kapacitor. I still prefer Curve as it has no dependencies and provides a GUI. The use case is quickly reviewing HA data to identify and characterise anomalies. 

On the more general topic I don't use InfluxDB since it doesn't use SQL and is therefore incompatible with the usual data wrangling tools.

Cheers
