### ISSUE TITLE
❇ Guacamole

### ISSUE THREAD

**Issue by cnaples** [hassio-addons/repository#118]
I think this would be awesome sitting on HA

https://hub.docker.com/r/guacamole/guacamole/

https://guacamole.apache.org/

<blockquote><div><strong><a href="https://hub.docker.com/r/guacamole/guacamole/">Docker Hub</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://guacamole.apache.org/">Apache Guacamole™</a></strong></div></blockquote>

**Comment by nickdaria** [comment]
I might take this on soon. I am in the process of moving all of my non-development containers onto one CPU, and Guacamole is one of the stacks I need to move over. I might as well try to build a hassio container for it so I don't have to manage any of my servers outside of hassio 🤷‍♂

**Comment by cnaples** [comment]
Wow that would be great. If there is anything I can do to help let me know!

**Comment by nickdaria** [comment]
Okay I decided to look a little deeper into this and I honestly don't remember setting this up on my regular server but it seems Guacamole's docker container isn't quite plug n' play.

According to the Docker Container, it requires 2 other images running and needs the use of scripts to initialize the database.

> "Using this image will require an existing, running Docker container with the guacd image, and another Docker container providing either a PostgreSQL or MySQL database.
> 
> The name of the database and all associated credentials are specified with environment variables given when the container is created. All other configuration information is generated from the Docker links.
> 
> Beware that you will need to initialize the database manually. Guacamole will not automatically create its own tables, but SQL scripts are provided to do this."

I can probably make it work using shell scripts in regard to the database initialization of the database, but I am not sure how to set up dependencies or multi-image hassio addons. I will look further into it.

**Comment by sinclairpaul** [comment]
I looked at this and had it running within a single container, the challenge was the image was very large.  If there is that much interest in it I can look to optimise it, but in the end it really only gave RDP connections as a benefit over the existing addons (i.e. SSH).  The UI wasn't exactly friendly either from what I recall.

**Comment by ThirteenTX** [comment]
Having a web front where you can directly manage all the machines on your network in a web page without needing to rely on VPN is pretty amazing. That coupled with the WoL in Home Assistant you could fire up your machine at home then connect to it from guacamole. You can also use it to ssh into accessory Raspberry Pis to make changes etc. I would totally use it. At the moment I will probably just run it from another Pi though.

**Comment by nickdaria** [comment]
I'll take a second look at this, but it will likely require more powerful hardware than the Pi and a MariaDB addon as well.

**Comment by boojew** [comment]
@nickdaria any luck with this?

**Comment by nickdaria** [comment]
> @nickdaria any luck with this?

I got it working but I believe it was a little resource intensive. I am swamped rn but I will try and clean it up a bit and push it. I am not sure it will work great with a Pi though.

**Comment by boojew** [comment]
I run on AMD64, so that would work for me.
