### ISSUE TITLE
HA + Node-Red Install Problem (YAML Code Error)

### ISSUE THREAD

**Issue by Herkeng** [hassio-addons/repository#121]
Installed Node-RED from Hassio add-on store and when i then I modifed my .YAML file with franks code, but since I really don't know anything about coding I have an issue. I know "Newbe".. Anyway here is the problem code according to the validation checker in HA.
ANY Help is greatly appreciated..

**Problem:** 
Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/configuration.yaml", line 84, column 3
expected <block end>, but found ','
  in "/config/configuration.yaml", line 84, column 20

**Code:**
Node-RED:
  "name": "NodeRED",
  "version": "1.2.3",
  "slug": "nodered",
  "description": "Flow-based programming for the Internet of Things",
  "url": "https://github.com/hassio-addons/addon-node-red",
  "webui": "[PROTO:ssl]://[HOST]:[PORT:1880]",
  "startup": "application",
  "arch": [
    "aarch64",
    "amd64",
    "armhf",
    "i386"
  ],
  "boot": "auto",
  "hassio_api": true,
  "hassio_role": "manager",
  "homeassistant_api": true,
  "host_network": true,
  "auth_api": true,
  "auto_uart": true,
  "gpio": true,
  "privileged": [
    "SYS_RAWIO"
  ],
  "devices": [
    "/dev/mem:/dev/mem:rwm"
  ],
  "apparmor": false,
  "map": [
    "config:rw",
    "share:rw",
    "ssl"
  ],
  "options": {
    "log_level": "info",
    "credential_secret": "",
    "http_node": {
      "username": "",
      "password": ""
    },
    "http_static": {
      "username": "",
      "password": ""
    },
    "port": 1880,
    "ssl": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem",
    "require_ssl": true,
    "system_packages": [],
    "npm_packages": [],
    "init_commands": []
  },
  "schema": {
    "log_level": "match(^(trace|debug|info|notice|warning|error|fatal)$)",
    "credential_secret": "str",
    "http_node": {
      "username": "str",
      "password": "str"
    },
    "http_static": {
      "username": "str",
      "password": "str"
    },
    "port": "port",
    "ssl": "bool",
    "certfile": "str",
    "keyfile": "str",
    "require_ssl": "bool",
    "system_packages": [
      "str"
    ],
    "npm_packages": [
      "str"
    ],
    "init_commands": [
      "str"
    ],
    "i_like_to_be_pwned": "bool?",
    "leave_front_door_open": "bool?"
  },
  "environment": {
    "LOG_FORMAT": "{LEVEL}: {MESSAGE}"
  },
  "image": "hassioaddons/node-red-{arch}"

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/addon-node-red">hassio-addons/addon-node-red</a></strong></div><div>Node-RED - Community Hass.io Add-on for Home Assistant - hassio-addons/addon-node-red</div></blockquote>

**Comment by ludeeus** [comment]
The code you posted is inside the container and used by the addon, you should **not** add this to your `configuration.yaml` file.
Please follow the installation instructions for Node-RED
https://github.com/hassio-addons/addon-node-red#installation
