### ISSUE TITLE
❇ NetBox

### ISSUE THREAD

**Issue by bonanitech** [hassio-addons/repository#125]
# Motivation

Many of us have several devices in separate networks. It would be nice to have a tool like this to help us keep our environment well documented and organized.

## Refs

https://github.com/digitalocean/netbox

https://github.com/ninech/netbox-docker

<blockquote><img src="https://avatars1.githubusercontent.com/u/4650108?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/digitalocean/netbox">digitalocean/netbox</a></strong></div><div>IP address management (IPAM) and data center infrastructure management (DCIM) tool. - digitalocean/netbox</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/1080949?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ninech/netbox-docker">ninech/netbox-docker</a></strong></div><div>Docker tooling for NetBox. Contribute to ninech/netbox-docker development by creating an account on GitHub.</div></blockquote>

**Comment by ludeeus** [comment]
I like it! :D

**Comment by bonanitech** [comment]
I have a working version running locally and wanted to know if there is any interest in it becoming a community add-on.

**Comment by rpitera** [comment]
My network is small and pretty flat, so this would be overkill for me personally.  But you know I support anything you do, so if you go for it I will certainly help publicize it!  : )

**Comment by bonanitech** [comment]
Since there are not much people interested I'm closing this.

It was an awesome challenge, I've learned a lot!
