### ISSUE TITLE
Should the installation section be added to the j2 file?

### ISSUE THREAD

**Issue by timmo001** [hassio-addons/repository#127]
# Problem/Motivation

Most issues / support questions appear from users not reading the installation section of the docs. Perhaps if the installation section was added to the `.README.j2` file, this could be reduced. The link to the full docs works, putting this section on the store page could help as well as being a timesaver.

Just a thought, as even I will admit to not reading the docs. 🤣

## Proposed changes

- Add the `Installation` section from the main README to the `.README.j2` file.

**Comment by frenck** [comment]
IMHO it is already to long...

Maybe we should look into extending the "add-on" store.
E.g., by allowing to provide screenshots, instructions, descriptions and all kinds of stuff (things you see in a normal add-on store)

**Comment by timmo001** [comment]
True. The add-on store could do with a major refurb. I'm not sure if it's still as hard now, but the last time I tried to develop / test on the frontend with hassio, it was so much of a pain I gave up 😆
