### ISSUE TITLE
ZeroTier hassio

### ISSUE THREAD

**Issue by mbriney** [hassio-addons/repository#134]
Can you consider adding ZeroTier to the community Hass.io plugins?
https://github.com/TomCzHen/hassio-addon-zerotier-one

<blockquote><img src="https://avatars3.githubusercontent.com/u/8936899?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/TomCzHen/hassio-addon-zerotier-one">TomCzHen/hassio-addon-zerotier-one</a></strong></div><div>Contribute to TomCzHen/hassio-addon-zerotier-one development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
I actually have one ready myself, so, no.

**Comment by mbriney** [comment]
Even better!  Can't wait.

**Comment by frenck** [comment]
Look at it again, it is actually not bad! A little bit outdated and some weirdness, but in general, not bad.

**Comment by fernandex00** [comment]
Wow, just see this?this is great, when it will be available frenck?
