### ISSUE TITLE
How to mount host folder to container in addon?

### ISSUE THREAD

**Issue by lpt2007** [hassio-addons/repository#137]
How can I mount host folder to container like on docker run command:
`-v /folder/on/host:/folder/in/container`

I try inside `config.json`:
```
  "devices": [
    "/folder/on/host:/folder/in/container:rw"
  ],
```
error:
`ERROR (SyncWorker_11) [hassio.docker] Can't start addon_local_kodi: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/folder/on/host": no such file or directory")`

**Comment by frenck** [comment]
You can't and are in the wrong place for creating this issue.
Please try the forums or discord chat.
