### ISSUE TITLE
❇ Bitwarden

### ISSUE THREAD

**Issue by Tommatheussen** [hassio-addons/repository#142]
# Problem/Motivation
> The easiest and safest way for individuals, teams, and business organizations to store, share, and sync sensitive data.

[Bitwarden](https://bitwarden.com) is an open-source password manager (Yay for open source! 🙌). I've been using it myself for about a year now, and so far it's been a solid replacement for my LastPass configuration from before. Earlier this month I found that Bitwarden actually allows a self-hosted setup. I didn't try it out myself yet, but it would be really cool if this could make it into an addon into HassIO. 

From what I can gather quickly, they have a GitHub repository containing the Server setup code (https://github.com/bitwarden/server), complete with Docker images.
Combined with their help documents: https://help.bitwarden.com/article/install-on-premise/ regarding self-hosting, I think it might be worth to give it a shot.

*Note:* The only limiting factor I've seen so far, might be hardware requirements: 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/13683094/54759863-3a5dbf00-4bef-11e9-8b6d-357236628777.png">

<blockquote><img src="https://avatars3.githubusercontent.com/u/15990069?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/bitwarden/server">bitwarden/server</a></strong></div><div>The core infrastructure backend (API, database, Docker, etc). - bitwarden/server</div></blockquote>
<blockquote><div><strong><a href="https://help.bitwarden.com/article/install-on-premise/">Installing and deploying | Bitwarden Help & Support</a></strong></div></blockquote>

**Comment by sinclairpaul** [comment]
Got excited by this, unfortunately SQLServer and the 2GB requirement is likely a killer, think of the poor Pi's :)

**Comment by sjabby** [comment]
This version in rust is much more lightweight: https://www.google.com/amp/s/blog.linuxserver.io/2019/01/15/self-hosting-bitwarden/amp/

**Comment by frenck** [comment]
Done! 🎉 

https://github.com/hassio-addons/addon-bitwarden
