### ISSUE TITLE
❇ Unifi Video

### ISSUE THREAD

**Issue by oyvindkinsey** [hassio-addons/repository#143]
Unifi Video is an NVR controller for the Unifi Video line of cameras. It is available as free software, and can be installed in Docker. 
https://hub.docker.com/r/pducharme/unifi-video-controller/ is an example of an existing dockerized installation.

Similar to how Hassio boasts a Unifi Controller addon, it would be great if the Unifi Video was also available, especially as it would be complementary to the UVC component.

**Comment by frenck** [comment]
Thanks for the idea!
I personally do not own those, so building an add-on for it, will not be something I can do.

**Comment by oyvindkinsey** [comment]
After having looked a bit closer, Unifi Protect might be a better target these days, but as long as the there's no proper component for interacting with Unifi Protect like there is for Video (UVC), Video might still be a better option for now.

@frenck, since you put up the Unifi Controller add-on, and I would presume that the installation procedures for most Unifi products are similar, could you point to a guide on how this might work? Is there maybe a set of preferred guides for how to convert various tools into add-ons?

**Comment by frenck** [comment]
The UniFi stuff is really hard to run and maintain in an add-on, while supporting multiple platforms.

At this point, I don't see this happening any time soon, so I'll go ahead and close this one up.
