### ISSUE TITLE
This add-on is not available on your system.

### ISSUE THREAD

**Issue by jeraisel** [hassio-addons/repository#149]
Hi,
I tied to install Portainer and  Log Viewer and on install I get the message 

> This add-on is not available on your system.

I have a raspberry pi 1 B+

an have installed hassio Home Assistant 0.91.4.

![image](https://user-images.githubusercontent.com/12325638/56937496-f2d32880-6af4-11e9-859c-3a0d42257e29.png)

is there a way to install these software?

Thank you

**Comment by r3mcos3** [comment]
For some add-ons you need to be on the latest version 0.92.0 or 0.92.1

**Comment by jeraisel** [comment]
Thanks 

But 0.92.1 was just available this week? At least was when the update appeared on the dashboard tab

![image](https://user-images.githubusercontent.com/12325638/56938285-e355de80-6af8-11e9-883f-a557ccec5266.png)

if I update I will be able to install them?

**Comment by r3mcos3** [comment]
Yes,

**Comment by jeraisel** [comment]
ok, thanks
