### ISSUE TITLE
Official Motion addon

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/repository#150]
# Problem/Motivation
This addon (https://github.com/lovejoy777/hassio-addons/tree/master/motion) makes it dead easy to use USB cameras with Hassio, [as I do here](https://www.hackster.io/robin-cole/motion-activated-image-capture-and-classification-of-birds-6ef1ce), and does not require that you use the motioneye-OS on the pi

**Comment by frenck** [comment]
The problem is that addon works only on A pi, because of that.

Not going to support a single device on this repository.
