### ISSUE TITLE
OctoPrint

### ISSUE THREAD

**Issue by nickdaria** [hassio-addons/repository#154]
OctoPrint is a very powerful web interface and print server for 3D Printers. It is known for being used on Raspberry Pi boards, however the software distribution is multiarch. I am looking to port the following community member maintained container as unlike the official container his is multiarch. 

I will most likely start work in the next week if the author and container manager give permission.

[OctoPrint](https://octoprint.org/)
[Docker Hub](https://hub.docker.com/r/nunofgs/octoprint/)

**Comment by frenck** [comment]
There is nothing multiarch about that... just standard work. Similar to how our containers are built (except the community add-ons are build natively, without qemu).
