### ISSUE TITLE
e4E

### ISSUE THREAD

**Issue by RudolfRendier** [hassio-addons/repository#155]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by RudolfRendier** [comment]
Sorry about this, created issue accidentally

**Comment by frenck** [comment]
@RudolfRendier No problem m8! That happens 👍
