### ISSUE TITLE
Addons on raspberry pi 4

### ISSUE THREAD

**Issue by hugosbnarciso** [hassio-addons/repository#157]
# Problem/Motivation

Addons don't work on Raspberry Pi 4

## Steps to reproduce

Upgrade to Raspberry Pi 4

**Comment by hugosbnarciso** [comment]
[https://www.dropbox.com/s/t7jmqvgw7oq8t2p/Screen%20Shot%202019-07-19%20at%2012.54.44.jpg](url)

**Comment by frenck** [comment]
Probably because you are running on HassOS 3.3 Beta for the Raspberry Pi 4.
This is a known issue with HassOS (that's is why it is beta).
Not munch I can do about that.
