### ISSUE TITLE
Not possible to add this repository to hassio

### ISSUE THREAD

**Issue by a-sp** [hassio-addons/repository#165]
# Problem/Motivation

Not possible to add  this custom repository to add-on store.

## Expected behavior

> (What you expected to happen)

## Actual behavior

```
[19-10-12 11:29:48 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/8dfed277/nut/config.json: required key not provided @ data['arch']. Got None
19-10-12 11:29:48 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/53caca22/nextcloud/config.json: required key not provided @ data['arch']. Got None
19-10-12 11:29:48 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/53caca22/mopidy_alpine/config.json: required key not provided @ data['arch']. Got None
19-10-12 11:29:48 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/53caca22/kanboard/config.json: required key not provided @ data['arch']. Got None
19-10-12 11:29:48 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/53caca22/snapcastserver/config.json: required key not provided @ data['arch']. Got None]
```

## Steps to reproduce

Simply add https://github.com/hassio-addons/repository as repository 

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Community Hass.io Add-ons for Home Assistant. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
Not sure what you are trying to add, but this repository does not have a snapcastserver, kanboard, nextcloud or any of those listed add-ons.....

**Comment by a-sp** [comment]
Shame on me... I didn't double check. I actually jumped into this repository from here: https://github.com/hassio-addons/addon-nut

But you are right, there is no nut addon in this repositor

**Comment by a-sp** [comment]
Do you know where can I found the addon-nut?

**Comment by frenck** [comment]
@a-sp The NUT add-on on this GitHub organization isn't finished or production-ready and should therefore not be used. Hence it is not part of the repository.
