### ISSUE TITLE
Firefly III 

### ISSUE THREAD

**Issue by gieljnssns** [hassio-addons/repository#167]
[Firefly III](https://github.com/firefly-iii/firefly-iii)

![](https://firefly-iii.org/static/screenshots/4.7.4/budget.png)

A FREE AND OPEN SOURCE PERSONAL FINANCE MANAGER

"Firefly III" is a self-hosted financial manager. It can help you keep track of expenses, income, budgets and everything in between. It supports credit cards, shared household accounts and savings accounts. It’s pretty fancy. You should use it to save and organise money.

Firefly III is pretty feature packed. Some important stuff first:

- It is completely self-hosted and isolated, and will never contact external servers until you explicitly tell it to.

- It features a REST JSON API that covers almost every part of Firefly III.

- There are many translations available.

- All pages feature help texts and support popups.

There is a [docker version](https://docs.firefly-iii.org/installation/docker)

**Comment by sinclairpaul** [comment]
I don't understand what this issue is logged for.  Perhaps you could elaborate your actual issue?

**Comment by sinclairpaul** [comment]
Sorry it's early in the morning, I'm assuming this is an add-on request.  It's already done and on the edge repo at the moment.

**Comment by gieljnssns** [comment]
Yes it was a request...
On the edge-repo? When will it be available on the main repo?
