### ISSUE TITLE
zwave2mqtt Dev version

### ISSUE THREAD

**Issue by foxy82** [hassio-addons/repository#169]
# Problem/Motivation

To test moving to zwave 1.6 I need to use the zwave2mqtt Dev docker. Which is tagged 2.0.6-dev

Details here: https://github.com/robertsLando/Zwave2Mqtt-docker/blob/master/README.md

Can we create a Dev version to install as a hasio option?

<blockquote><img src="https://avatars2.githubusercontent.com/u/11502495?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/robertsLando/Zwave2Mqtt-docker">robertsLando/Zwave2Mqtt-docker</a></strong></div><div>Docker container for Zwave2Mqtt Gateway and Control Panel app - robertsLando/Zwave2Mqtt-docker</div></blockquote>

**Comment by frenck** [comment]
The current edge version already runs ozw 1.6.

Use this repository: https://github.com/hassio-addons/repository-edge

Please note, those are dev/edge builds and are not recommended for production use.
