### ISSUE TITLE
Feature request: Is it possible to have a TURN server, needed for VOice chat ?

### ISSUE THREAD

**Issue by Klagio** [hassio-addons/repository#171]
As in subject, thanks

www.webrtc-experiment.com/docs/TURN-server-installation-guide.html#coturn

**Comment by timmo001** [comment]
I do like this idea. What would complement this, is a web client which is able to make the calls and maybe in future integrate with ha with autodiscovery

**Comment by Klagio** [comment]
> I do like this idea. What would complement this, is a web client which is able to make the calls and maybe in future integrate with ha with autodiscovery

exactly
