### ISSUE TITLE
no light switch button

### ISSUE THREAD

**Issue by czadikem** [hassio-addons/repository#179]
When i try to control my light switch I cannot turn it on or off in the webui.
  How can I control my light switch with this webui?

**Comment by frenck** [comment]
So this is the repository, containing all community add-ons.

I'm not sure if you question is about a specific addon or Home Assistant itself, or maybe even any of the integrations.

If you have a question about a specific add-on, please join our discord channels or use the community forums. If you have a bug, please raise an issue on the repository of that specific add-on. If you have an issue with a Home Assistant integration, please raise an issue at the Home Assistant GitHub.

I'm pretty sure you are in the wrong location right now.

../Frenck
