### ISSUE TITLE
❇ OpenVPN

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#18]
# Problem/Motivation

Create an add-on for OpenVPN. 
It would be awesome if there was some kind of web interface allowing the user to easily manage the accounts.

## References

https://pritunl.com/
https://openvpn.net/index.php/access-server/overview.html
http://www.pivpn.io/

**Comment by TheSkorm** [comment]
I made a very basic addon here -> https://github.com/TheSkorm/hassio-openvpn

**Comment by mvillarejo** [comment]
I'd love to see this wokring, there seems to be already good options around:
https://github.com/kylemanna/docker-openvpn

**Comment by frenck** [comment]
I've found a way to get this thing working. I will be working this pretty soon.

**Comment by danielsjf** [comment]
@frenck is there any version already available for testing?

**Comment by frenck** [comment]
@danielsjf Nope

**Comment by charlietomo** [comment]
I'm keen to see this working and happy to test as and when required.

**Comment by Emacee** [comment]
Interested in the progress of development of this add-on. Would be wonderful to run this on the same Pi that Hass.io is running on. Better than setting up VPN's on routers afaik.

**Comment by rbray89** [comment]
I've got an addon that sets everything up for you here: https://github.com/rbray89/hassio-addons/blob/master/openvpn_server

Note that it doesn't have a clean way of revoking clients (you have to reissue to all) but may be added in the future.

**Comment by frenck** [comment]
Thanks @rbray89,

I've considered such an approach in the past as well, but not being able to revoke is a big no-no for me.

**Comment by danielsjf** [comment]
Is this one an option?
https://mobilejazz.com/blog/setting-up-a-vpn-server-in-5-minutes-with-docker/

It supports multiple users.

**Comment by frenck** [comment]
@danielsjf I know how to set up a VPN server manually, thanks.

**Comment by rbray89** [comment]
@frenck:
Yeah, My thinking is either to either add a separate 'revoke' list, or keep tabs on the user list on startup, and revoke any users not in the config, and add any users in the config that don't yet have a cert generated.

**Comment by Pre10der** [comment]
@frenck - is this of any use (OpenVPN based)? https://github.com/InnovativeInventor/docker-pivpn

PiVPN includes revoke capabilities.

**Comment by frenck** [comment]
I'm familiar with PiVPN, but thanks for the suggestion.

**Comment by webartoli** [comment]
PiVPN by the way is no longer maintained

**Comment by larsklitzke** [comment]
Not quite related to setting up a OpenVPN server but for those of you wanting to connect your home assistant server to a remote OpenVPN server I created an addon for the client in https://github.com/larsklitzke/homeassistant-openvpn-client

I currently use it to tunnel the requests of Google Assistant through the VPN tunnel via a remote server to my local home assistant installation.

**Comment by lopesdasilva** [comment]
> I've got an addon that sets everything up for you here: https://github.com/rbray89/hassio-addons/blob/master/openvpn_server
> 
> Note that it doesn't have a clean way of revoking clients (you have to reissue to all) but may be added in the future.
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/1095572?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/2d7ebf10f3aeb8a990e0c9d6c9efa4d9f103977c/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f66617669636f6e2e69636f"> GitHub**[rbray89/hassio-addons](https://github.com/rbray89/hassio-addons)**Custom Hassio Addons. Contribute to rbray89/hassio-addons development by creating an account on GitHub.

Does this still work? I've added your repo but when I press install nothing happens neither show on logs

**Comment by rbray89** [comment]
@lopesdasilva Yeah, it should work. Install can take a while as it has to build the container itself. Nothing in the Hassio System logs?

**Comment by lopesdasilva** [comment]
On the browser I see a XHR request being made and the response is:

> {
    "result": "error",
    "message": "Unknown Error, see logs"
}

But that's it.

**Comment by rbray89** [comment]
@lopesdasilva Ah, seems that when I added armv7 I didn't think to check that the base docker image existed. Reved the docker images and the version. *Should* work now, but untested.

**Comment by frenck** [comment]
From the community add-ons project, we are not going to provide OpenVPN.
Instead, we now provide WireGuard as a VPN solution:

https://frenck.dev/introducing-wireguard-vpn-for-hass-io/
