### ISSUE TITLE
Pipeline job for beta & stable broken

### ISSUE THREAD

**Issue by shawly** [hassio-addons/repository#182]
# Problem/Motivation

I'm trying to use your pipeline jobs for deploying my images and publishing my repository. For my EDGE repo and images everything seems to work just fine, but when I want to push a beta release or a stable it stops in the middle of the deploy step.

Here is the failed pipeline job:

https://gitlab.com/shawly/hassio-api-scapegoat/pipelines/135192347

It seems to be stuck right after the before_script is done:

https://github.com/hassio-addons/organization/blob/eaf2fcdb7c8ecc99a1910c17efbd1acb1f7cc5bc/gitlabci/addon.yml#L134

Can you help me identifying the issue here?

<blockquote><img src="https://assets.gitlab-static.net/assets/gitlab_logo-7ae504fe4f68fdebb3c2034e36621930cd36ea87924c11ff65dbcb8ed50dca58.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/shawly/hassio-api-scapegoat/pipelines/135192347">Pipeline · shawly / hassio-api-scapegoat</a></strong></div><div>A simple API gateway with failover capabilities for Home Assistant REST sensors and the likes.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/organization">hassio-addons/organization</a></strong></div><div>Repository for origanization wide discussions, issues and Probot settings - hassio-addons/organization</div></blockquote>

**Comment by frenck** [comment]
Be sure to define your pipeline secrets.

**Comment by shawly** [comment]
They are defined, otherwise my edge pipeline jobs wouldn't work too.
