### ISSUE TITLE
❇ Wiki.js

### ISSUE THREAD

**Issue by tjorim** [hassio-addons/repository#184]
# Problem/Motivation

Managing documentation and other stuff locally is always nice.
Even for private use, a wiki is great to keep track of changes.
Wiki.js is a stable and feature rich platform for deploying a wiki.

https://wiki.js.org/
It has various modules
and a provided Docker image

<blockquote><div><strong><a href="https://wiki.js.org/">Wiki.js</a></strong></div><div>The most powerful and extensible open source Wiki software.</div></blockquote>

**Comment by tjorim** [comment]
Not a dupe...

**Comment by AndyRPH** [comment]
> Potential duplicates:
> 
> * [#39] ❇ Pilight (64%)

**Comment by donchrizz** [comment]
I would love to see a wiki.js add-on as well!
