### ISSUE TITLE
SSH & WebTerminal add-on is not available in add-on store

### ISSUE THREAD

**Issue by lucky62** [hassio-addons/repository#186]
Where is SSH & WebTerminal addon?

![image](https://user-images.githubusercontent.com/16965519/80630958-5029ee80-8a55-11ea-89b4-6e0bafa7749f.png)

**Comment by tjorim** [comment]
https://github.com/hassio-addons/addon-ssh/issues/138

**Comment by lucky62** [comment]
thanks.
