### ISSUE TITLE
Squeezelite standalone 

### ISSUE THREAD

**Issue by large** [hassio-addons/repository#194]
# Motivation
Did not find a plugin to run Squeezelite for home assistant

## Expected behavior
That someone already had done this plugin :)

## Actual behavior
I took the time to create my first HA plugin, so if you are in need for a Squeezelite player (standalone) please visit
https://github.com/large/hassio-addons

## Proposed changes
My skills in docker, compiling for linux and packing are limited. So I copied the stuff by the best.
Because of my low skills the Squeezelite only works on x86/x64, since I did not find a way to include them both.

**Comment by frenck** [comment]
Not sure why you've created this issue?

**Comment by large** [comment]
@frenck that was misplaced so it can just be closed.
I later found the HA community forum to actually publish such info.
