### ISSUE TITLE
Speedtest

### ISSUE THREAD

**Issue by manzari** [hassio-addons/repository#200]
I want to monitor my networks internet speeds in Hass but could not find an Add-on to do so in this Repo. Actually I could not find one anywhere. [So I created a simple one.](https://github.com/manzari/hass-speedtest/tree/master/speedtest)

If interested I could provide a pull request to add the plugin to this repository.
I would also continue to maintain it.

**Comment by frenck** [comment]
We are currently not accepting new third-party add-ons in the repository. It is perfectly fine to maintain your own repository.

**Comment by bonanitech** [comment]
> I want to monitor my networks internet speeds in Hass

You could use the [Speedtest.net](https://www.home-assistant.io/integrations/speedtestdotnet/) integration for that.

**Comment by manzari** [comment]
> > I want to monitor my networks internet speeds in Hass
> 
> You could use the [Speedtest.net](https://www.home-assistant.io/integrations/speedtestdotnet/) integration for that.

oh damn I didn't see that one
