### ISSUE TITLE
❇ BroadlinkManager

### ISSUE THREAD

**Issue by sim-san** [hassio-addons/repository#203]
BroadlinkManager is a Flask powered, easy to use system that helps you to work with Broadlink Devices. With Broadlink manager you can:

-  Scan your network for devices.
-  Lean and Send IR or RF Codes
-  Random generate RF Codes
-  Change Repeats for Existing codes (IR/EF)

BroadlinkManager [Docker Image](https://github.com/t0mer/broadlinkmanager-docker)

This would be a helpful tool for setting up the [Broadlink integration](https://www.home-assistant.io/integrations/broadlink/)

**Comment by frenck** [comment]
I think this is stuff that should be added to the integration. It seems weird to split that stuff over multiple sources.
