### ISSUE TITLE
Sonarr/Radarr

### ISSUE THREAD

**Issue by AlecRust** [hassio-addons/repository#205]
## Proposed changes

Just wondered if [Sonarr](https://sonarr.tv/) and [Radarr](https://radarr.video/) have been considered as add-ons?

Currently these can be set up separately outside of HA but it would be great to have an add-on for them. They would compliment other add-ons such as [Transmission](https://github.com/pierrickrouxel/hassio-addon-transmission).

Currently there are official Home Assistant integrations for both Sonarr and Radarr but no decent up to date add-ons for them. Based on the number of queries I've found about setting these up within Home Assistant I think there might be some demand.

**Comment by frenck** [comment]
They have been considered and will not be added to this repository.
