### ISSUE TITLE
Support for custom resolutions

### ISSUE THREAD

**Issue by alekseybaranenko** [hassio-addons/repository#207]
# Problem/Motivation

I have a camera with resolutions other than the standard.
The resolution of the cameras are: 2304x1296 or 640x352.
In VLC the protocol is "MPEG-H Part2 / HEVC (H.265) (hevc)".
I use MotionEye as an Addon in HA (raspberrypi 4).
It is only on the gray screen, and after about 10 seconds, it recharges all cameras.

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

There is no error in the log (log_level: trace), I can only see that it is in a loop reloading all cameras.

## Proposed changes

In other forums, I read that in MotionEyeOS it is possible to correct this, adding the camera resolution manually via file.
As it is an Addon in HA, I do not have access to this configuration.
The resolution setting when adding a camera does not work in this case.

**Comment by frenck** [comment]
Wrong repo?
