### ISSUE TITLE
Fresh Install results in 502 Bad Gateway or 401: Unauthorized

### ISSUE THREAD

**Issue by NVader2000** [hassio-addons/repository#208]
502: Bad Gateway

To be honest my first attempt actually worked but then I screwed something up and could not figure out how to reset Home Panel. So I formatted and reimaged my HA. Ever since then it does not matter what I do it ends up with either one of three results.

1. 502: Bad Gateway
2. 401: Unauthorized
3. Prompted to sign into my HA (weird)

Please advise.

**Comment by frenck** [comment]
Not sure what your problem is about, but the repository you are reporting your issue seems wrong.
Please make sure you are reporting your issues in the right place. Thanks 👍
