### ISSUE TITLE
Open Tasmoadmin via Nabucasa

### ISSUE THREAD

**Issue by duesseldorferjung** [hassio-addons/repository#209]
# Problem/Motivation

Can not open Tasmoadmin via Nabucasa

## Expected behavior

Click on open webui and have the page displayed

## Actual behavior

Timeout of page

## Steps to reproduce

Connect HA via Nabucasa and try to open Tasmoadmin

**Comment by frenck** [comment]
Not all add-ons support Ingress (which is required for that). Unfortunately, that is often a limitation of the application running in the add-on itself.

In this case, TasmoAdmin won't work via Ingress.
