### ISSUE TITLE
secrets.yaml integration does not seem to work

### ISSUE THREAD

**Issue by PanMat** [hassio-addons/repository#210]
# Problem/Motivation
AppDeamon4 fresh install, the secrets.yaml integration seems broken
> (Why the issue was filed)
This is an important aspect to keep sensitive information out of the app code
## Expected behavior
Expected "!secret" to work but it is not working
> (What you expected to happen)
AppDaemon scripts reading secrets.yaml from config directory
## Actual behavior
It does not read the secrets.yaml file from config directory
> (What actually happened)
Nothing
## Steps to reproduce
1. Install HA instance on a Pi4
2. install AppDaemon from add-on store
3. In the secrets.yaml add "phrase: "Tell me a secret!!""
4. In app.yaml add "phrase: !secret phrase"
5. In the AppDaemon Admin console see logs that says "ValueError: phrase not found in secrets file"
> (How can someone else make/see it happen)
Follow above steps
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not the add-on repository, secondly, add-ons wrap software. Please report your issue with AppDaemon itself with the AppDaemon project.
