### ISSUE TITLE
MagicMirror2 Addon still usable?

### ISSUE THREAD

**Issue by DanielHabenicht** [hassio-addons/repository#212]
# Problem/Motivation

The MagicMirror Module is currently archived https://github.com/hassio-addons/addon-magicmirror/, but still [listed on the Edge Addons Page](https://addons.community/edge/#magicmirror2)

## Expected behavior

I would have thought that there are only addons listed that are at least in a working state, but definitely not addons that should not be used anymore.

## Actual behavior

I wanted to use the module and I still don't know if it works or if it is safe to use.

## Proposed changes

Remove it from the list. 

## Furthermore

As I still want to have MagicMirror running with Hassio my leading question is why the addon was discontinued and if there is a way to make it useful again.

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/104133778-fcaec500-5385-11eb-80c3-87d4141905f6.png)


Do whatever you want with it. It is archived. Not my concern or problem at this point.

**Comment by DanielHabenicht** [comment]
@frenck thanks for your time. Sorry if I didn't make it clear. My question was: Do you know the reason behind it being archived? Did it hit any barrier that makes it not worth continuing? I just wanted to ask before wasting time trying to make it work. 

Also, I think it might be a good idea to move deprecated add-ons to another section of the [Edge Add-Ons Page](https://addons.community/edge/#warning-this-is-an-edge-repository) (hit me up, I gladly provide a PR)

**Comment by frenck** [comment]
It was never released. Nobody cared. repository closed.

**Comment by DanielHabenicht** [comment]
K, thanks!
