### ISSUE TITLE
❇  Jupyter Lab Server

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#22]
# Problem/Motivation

Jupyter notebook server with path to the database for analysis.

As suggested on Twitter by Robin Cole:
https://twitter.com/robmarkcole/status/925257850519281664

# Ref

http://jupyter.org/
https://try.jupyter.org/
https://home-assistant.io/docs/ecosystem/notebooks/
http://jupyter-notebook.readthedocs.io/en/stable/notebook.html
https://github.com/home-assistant/home-assistant-notebooks

**Comment by robmarkcole** [comment]
Making progress on the analysis of db data 

http://nbviewer.jupyter.org/github/robmarkcole/HASS-data-science/blob/master/HASS%20data%20science%2022-11-2017.ipynb

**Comment by frenck** [comment]
Updated the ticket to use Jupyter Lab instead of Notebook

**Comment by DanielXYZ2000** [comment]
Maybe there is a way that example notebooks can easy be commited by the community.

**Comment by frenck** [comment]
@DanielXYZ2000 I've added the GitHub extension of JupyterLab to stimulate that a little.
