### ISSUE TITLE
❇  Happy Bubbles presence server [$15]

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#25]
# Problem/Motivation

Easy presence detection with Bluetooth beacons

## Ref

https://www.happybubbles.tech/
https://github.com/happy-bubbles/presence
https://home-assistant.io/components/sensor.mqtt_room/
https://twitter.com/oobie11/status/925438985282842624

**Comment by robmarkcole** [comment]
Another ref, reported [on this thread](https://community.home-assistant.io/t/presence-detection-with-low-cost-ble-devices-and-raspberry-pi-zero-w/28173):

https://github.com/mKeRix/room-assistant

**Comment by KKlitgaard** [comment]
That would be awesome!

**Comment by frenck** [comment]
The add-on is now available as a developer preview.

Add `https://github.com/hassio-addons/repository-edge` to your add-on repositories in Hass.io and it will be available.

**Comment by frenck** [comment]
🎉 This add-on has been released and is available in all our repositories.
