### ISSUE TITLE
Update for zwavejs2mqtt not showing up

### ISSUE THREAD

**Issue by altaic** [hassio-addons/repository#259]
# Problem/Motivation

The `zwavejs2mqtt` add-on was updated to v0.4.0 a few hours ago, but isn't showing up in my home assistant supervisor instance.

## Expected behavior

The update should show up in supervisor so users can install it.

## Actual behavior

Supervisor does not show the update, so we're stuck on v0.3.0.

## Steps to reproduce

Open supervisor in home assistant, go to the Add-On Store tab, click on Z-Wave JS to MQTT, observe that the version is v0.3.0.

## Proposed changes

I'm not sure why the update isn't showing up. Is there a cache that I can clear somewhere, or is it something else? I've tried restarting home assistant, supervisor, the zwavejs2mqtt add-on, and finally the whole system.

**Comment by sinclairpaul** [comment]
Supervisor Tab, Addon Store, Three Dots top right, then reload.

**Comment by sinclairpaul** [comment]
If it still doesn't appear, please check the supervisor log.

**Comment by altaic** [comment]
Fantastic, thank you!
