### ISSUE TITLE
Jupyterlab v0.4.0 is not showing in supervisor

### ISSUE THREAD

**Issue by pdecat** [hassio-addons/repository#260]
# Problem/Motivation

The newly released v0.4.0 is not showing in supervisor.

## Expected behavior

I should either be able to update my Jupyterlab Lite v0.3.1 to Jupyterlab v0.4.0,
or install Jupyterlab v0.4.0 beside the old version.

## Actual behavior

Only Jupyterlab Lite v0.3.1 is showing in supervisor, both from stable and beta _Home Assistant Community Add-ons_ repositories.

## Steps to reproduce

1. Go to supervisor UI
2. Click Add-on Store tab
3. Search for `jupyter`

![image](https://user-images.githubusercontent.com/318490/107287241-fc2b4c00-6a61-11eb-878a-65d60687725f.png)
![image](https://user-images.githubusercontent.com/318490/107287558-65ab5a80-6a62-11eb-988f-46509001c289.png)

Note:  Reloading repositories does not help:

```
21-02-08 21:50:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons-development repository
21-02-08 21:50:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-02-08 21:50:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-02-08 21:50:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository-beta repository
```

## Proposed changes

Maybe an issue with the redirection from https://github.com/hassio-addons/addon-jupyterlab-lite to https://github.com/hassio-addons/addon-jupyterlab and/or the fact that both addons share the same `jupyterlablite` slug?

- https://github.com/hassio-addons/repository/blob/master/jupyterlablite/config.json#L3-L4
- https://github.com/hassio-addons/repository/blob/master/jupyterlab/config.json#L3-L4

**Comment by frenck** [comment]
That is a bug caused by me 😢

**Comment by frenck** [comment]
Fixed!

This does require an update of the add-on store (which will happen automatically in the next couple of hours). You can force it right now, by going into the add-on store, hit the three-dotted menu in the top right, and select reload. After that, the newer version (with the dropped/without "Lite") should be available.

**Comment by pdecat** [comment]
Update works, thanks!

![image](https://user-images.githubusercontent.com/318490/107288517-db63f600-6a63-11eb-9c9f-bf6362ab7d57.png)

![image](https://user-images.githubusercontent.com/318490/107288531-e159d700-6a63-11eb-97e3-035407aa6353.png)
