### ISSUE TITLE
❇ Airplay Audio Server

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#27]
# Problem/Motivation

AirPlay audio player/server based on shairport-sync.
Shairport Sync adds multi-room capability with Audio Synchronisation

## Ref

https://github.com/mikebrady/shairport-sync
https://twitter.com/andyzickler/status/925391527068753920

**Comment by alc7328** [comment]
Does this exist or it's in development? Would love to have AirPlay multi-room integrated with HA

**Comment by basveeling** [comment]
I found this add-on to work well: https://github.com/v3rm0n/addon-shairport-sync! It can be installed via Hassio repo https://github.com/v3rm0n/hassio.

**Comment by spartanunitato** [comment]
Hi! @basveeling how did you configure the options in home assistant? I am not getting any audio output even though I have selected my pi in airplay.

**Comment by basveeling** [comment]
Hi @spartanunitato. My shairport-sync hassio addon settings are as follows:

```
log_level: info
avahi_interfaces: ''
avahi_hostname: ''
avahi_domainname: local
airplay_name: Study
enable_ipv6: false
```

And I've selected my default audio output. It pretty much worked straight away for me. Do other audio-enabled hassio addons produce sound for you?

**Comment by spartanunitato** [comment]
`log_level: info
avahi_interfaces: ''
avahi_hostname: ''
avahi_domainname: local
airplay_name: Desktop
enable_ipv6: false`

This is my configuration, and it does not work. I am able to get audio output using the Spotify cast add-on in home assistant. 

I also get this error under logs (it repeats many times):
`ALSA lib dlmisc.c:287:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/alsa-lib/libasound_module_pcm_pulse.so ((null): Error loading shared library /usr/lib/alsa-lib/libasound_module_pcm_pulse.so: No such file or directory)`

**Comment by martinschilliger** [comment]
Is your home assistant running on 64bit? As I tried this it didn't work… 🤔 But I didn't debug in detail, just switched to 32bit again.

**Comment by spartanunitato** [comment]
@martinschilliger nope, I am running on a 32bit HassOS install. Could it be that I am using a raspberry pi 4b?

**Comment by martinschilliger** [comment]
@spartanunitato Nope, that cannot be the problem…

**Comment by spartanunitato** [comment]
@martinschilliger what version of home assistant are you running? I’m on 0.108.9 and hassOS 3.13

**Comment by basveeling** [comment]
FWIW: I'm running raspbian with hass.io docker install.

**Comment by martinschilliger** [comment]
Same here, HassOS 3.13 and 0.108.9
