### ISSUE TITLE
To what extent it is possible to customize sshd_config with this addon?

### ISSUE THREAD

**Issue by drew-kun** [hassio-addons/repository#294]
# Problem/Motivation

I am trying to implement the certificate based ssh authentication following [this tutorial](https://berndbausch.medium.com/ssh-certificates-a45bdcdfac39)

I have generated host and user certificates and now I want to add the following stanzas to the `/etc/ssh/sshd_config`:
```
HostCertificate /etc/ssh/KEYFILE-cert.pub
```
and
```
TrustedUserCAKeys /etc/ssh/CA.pub
```

## Expected behavior

After restart of an addon I expected the new configuration to stay in `sshd_config` and work.

## Actual behavior

The statements, mentioned above just disappear from `sshd_config`.

## Steps to reproduce

Please see the steps above.

## Proposed changes

It would be great to have this sort of control over sshd_config and to be able to implement certificate-based ssh authentication.

**Comment by sinclairpaul** [comment]
This is the wrong repo, assuming you are discussing the SSH addon the repo is at https://github.com/hassio-addons/addon-ssh where the documentation shows how to configure you public key.
