### ISSUE TITLE
Homebridge pin generated with additional dash

### ISSUE THREAD

**Issue by mihalski** [hassio-addons/repository#3]
The autogenerated home bridge pin is in the format 290--22-311 (with the double dash).

You cannot add it to the Home app unless you edit the config.json to remove the additional dash.

**Comment by frenck** [comment]
Thank for reporting this issue @mihalski, it is confirmed.
I will fix this as soon as possible.

**Comment by frenck** [comment]
I've applied a hotfix for this, will be releasing shortly.
