### ISSUE TITLE
❇ Syncthing

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#30]
# Problem/Motivation

Syncthing replaces proprietary sync and cloud services with something open, trustworthy and decentralized. Your data is your data alone and you deserve to choose where it is stored, if it is shared with some third party and how it's transmitted over the Internet.

## Ref

https://syncthing.net/

**Comment by bestlibre** [comment]
I already have a working add-on for syncthing on [my repo](https://github.com/bestlibre/hassio-addons). How can we prevent duplicate work ?

**Comment by frenck** [comment]
@bestlibre Thank you for your feedback. Great to see some things already being out there!
I don't mind giving users choices. Our add-on development workflows and design paradigms differ significantly.

**Comment by mzac** [comment]
This would be so awesome!  I'm currently using a dropbox sync however dropbox now limits the number of systems that can sync with the free account.  This could be great if it could bumped up in developement!

**Comment by frenck** [comment]
Is it in development. Current progress is around 70% I would say. Most of it is done.
