### ISSUE TITLE
InfluxDB 4.2.0 not picked up by auto release

### ISSUE THREAD

**Issue by shbatm** [hassio-addons/repository#313]
# Problem/Motivation

[InfluxDB v4.2.0](https://github.com/hassio-addons/addon-influxdb/releases/tag/v4.2.0) was released 13 days ago and hasn't been picked up by the auto release `addonsbot`. Release is not available for installation in the HA Supervisor

## Expected behavior

addonsbot to release new version.

## Actual behavior

4.1.1 is still in the repo as the current version from 2 months ago.

## Steps to reproduce

N/A

## Proposed changes

Manual update of 4.2.0 for influxdb

**Comment by michaelpiron** [comment]
With the release of v4.2.1 of the influxdb add-on, I guess this issue can be closed.. Unless someone wants to figure out the cause of this issue
