### ISSUE TITLE
Auto change of version in config.yaml of a addon

### ISSUE THREAD

**Issue by thecem** [hassio-addons/repository#318]
# Problem/Motivation

> (Why the issue was filed)

Auto versioning in config.yaml on repo tag

## Expected behavior

> (What you expected to happen)

change automatically the version Info in the addon config file by a new Tag of a repository.

## Actual behavior

> (What actually happened)

manual config of version 

## Steps to reproduce

> (How can someone else make/see it happen)

Don’t know!

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
? I'm confused about the issue you are trying to raise, could you explain which add-on we are talking about and what the problem is?

**Comment by thecem** [comment]
Im talking about evcc the main repo is in 

https://github.com/andig/evcc

the addon in:

https://github.com/andig/evcc-hassio-addon

we would like to update the version in config.yaml by Tag Update from here: 

https://github.com/andig/evcc/tags

How we could achieve this, is there a way?

Idea behind is, every time the main repo get a new tag, the version Info in config.yaml to get the update of the new evcc (main).

at the moment it works only without (version: latest) update, users have to uninstall and then reinstall the addon.

**Comment by frenck** [comment]
That repository is not related or affiliated with this add-on repository.
If you have a question or feature request for that add-on, please raise it in that repository instead.

Thanks 👍

**Comment by thecem** [comment]
I will, but could you give a hint how this versioning is made for community addons or original HA addons?

Is there an automatisation to set the versions in the config.yaml?

**Comment by frenck** [comment]
The official core add-on does it manually.

The community add-ons do it automated using GitHub Actions based on the GitHub Release tag. Those actions are public in each add-on repository.

**Comment by thecem** [comment]
Thanks a lot!

Do you have an link for more information in mind? This would very very helpful!

thanks in advance for your help!

**Comment by frenck** [comment]
Go to any of the community add-on repositories and check the github actions workflow?
