### ISSUE TITLE
❇ Gogs

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#32]
# Problem/Motivation

A painless self-hosted Git service.

## Ref
https://gogs.io/
https://try.gogs.io/
https://gogs.io/docs
https://gogs.io/docs/installation/install_from_binary

**Comment by thundergreen** [comment]
will this be made? Would love seing this

**Comment by frenck** [comment]
@thundergreen It is almost finished. Worked on this recently.

**Comment by thundergreen** [comment]
grat @frenck for the time being i installed it manually :) If you finished i'd like to transfer my repos to the addon.. you think it's possible?
