### ISSUE TITLE
snapshot_exclude' is deprecated, 'backup_exclude' should be used instead

### ISSUE THREAD

**Issue by Ace0510** [hassio-addons/repository#326]
# Problem/Motivation: 21-09-13 11:06:53 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not the adguard home repository.
