### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by brinzlee** [hassio-addons/repository#327]
Anybody come across this message…
“The client and server don’t support a common SSL protocol version or cipher suite.”
I’m getting this when trying to open the WebUI from TasmoAdmin. I've tried chrome and safari, Its been working fine for ages and now I can’t start it, I have deleted duckdns and reinstalled it, in case it was an ssl key error but that hasn’t worked…I’ve also cleared the browser cache but nothing gives
Add-on version: 0.15.0
You are running the latest version of this add-on.
System: Home Assistant OS 6.3 (aarch64 / raspberrypi4-64)
Home Assistant Core: 2021.9.4
Home Assistant Supervisor: 2021.09.0

** I have just seen there is an update 15.1 that addresses ssl protocols. I presume @frenck will be updating this in HomeAssistant shortly although I did notice this was updated back in May on Github.....Has this been overlooked ?

**Comment by frenck** [comment]
Please file the issue with the add-on repository that causes the issue. This issue is filed @ the whole "store".

**Comment by brinzlee** [comment]
The addon repository has been updated....Its the addon that you update in this store that has not been updated as I have mentioned in my comments above....

**Comment by frenck** [comment]
Aan will take a look soon. Still recovering an need to catch up on a lot

**Comment by brinzlee** [comment]
This is exactly what I am talking about.....The issue has not been resolved and now you are marking it as stale....read the thread mr bot !! It needs to be updated to 15.1 in the store !!

**Comment by frenck** [comment]
Fixed in with the latest release
