### ISSUE TITLE
❇ CUPS / Print server

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#33]
# Problem/Motivation

CUPS print server and printing drivers, so a user can hook up a printer to the home network.

## Ref

https://home-assistant.io/components/sensor.cups/
https://www.cups.org/

**Comment by messismore** [comment]
Would be cool if it hooked into Home Assistant to automatically switch the printer on and off.

**Comment by matteos1** [comment]
there is a add on for cups?

**Comment by hugodelaroza** [comment]
It would be great to have an addon to share an old usb printer to the network and use hassio raspberry as a print server

**Comment by matteos1** [comment]
there is some hope regarding this add on?

**Comment by dereitz** [comment]
I'm guessing there's only hope if enough people comment and/or provide a thumbs up...

**Comment by MatteoGheza** [comment]
Any update on this?
