### ISSUE TITLE
Add Autossh add on

### ISSUE THREAD

**Issue by xchwarze** [hassio-addons/repository#332]
Hello team!
For more than 2 years I have been working on this fork that I use to connect to HA externally
https://github.com/xchwarze/hassio-addons-legacy/tree/master/hass_tunnel
Since it works so well I decided to redo the add on to be able to present it here.
Would you be interested in adding it?
The repo of the version that I am working with that idea is this 
https://github.com/xchwarze/hassio-addons/tree/master/autossh

**Comment by frenck** [comment]
This is not an issue?

I have no interest in adding it.

**Comment by xchwarze** [comment]
sorry @frenck thought the title "community" of the repo name came because it was... a community? 
I guess it should be called "Home Assistant Franck Add-ons" so that these misunderstandings don't happen... 
Anyway I think they should indicate in https://developers.home-assistant.io/docs/add-ons that they do not accept contributions from third parties
