### ISSUE TITLE
Cannot download zwave-js to mqtt plugin

### ISSUE THREAD

**Issue by Arthedian** [hassio-addons/repository#335]
# Problem/Motivation

I cannot install Zwave-js to MQTT plugin

## Actual behavior

When trying to install new version of this plugin it throws me an error:
`Can't install ghcr.io/hassio-addons/zwavejs2mqtt/aarch64:0.26.0: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.26.0&fromImage=ghcr.io%2Fhassio-addons%2Fzwavejs2mqtt%2Faarch64: Internal Server Error ("Get https://ghcr.io/v2/: dial tcp: lookup ghcr.io on 127.0.0.1:53: server misbehaving")`

## Steps to reproduce

I firstly uninstalled the old version, and now I am trying to install the new one

**Comment by frenck** [comment]
> Internal Server Error ("Get https://ghcr.io/v2/: dial tcp: lookup ghcr.io on 127.0.0.1:53: server misbehaving"

This is not an add-on or repository issue, but an issue with your networking.

**Comment by Arthedian** [comment]
@frenck Do you now what is the issue? I am able to connect to the internet on the same network and even I am able to connect to the HA from outside of the network via public IP

**Comment by frenck** [comment]
@Arthedian I don't know you system or network, so nope. Sorry.

**Comment by Arthedian** [comment]
How do you know, that it is network issue? Because I moved the RPI to different location with different network (very simple one - one router, one switch, that is all) and I have still the same issue.
