### ISSUE TITLE
❇ Plex Server

### ISSUE THREAD

**Issue by arsaboo** [hassio-addons/repository#34]
# Problem/Motivation

[Plex](https://www.plex.tv/) is one of the common things that many people run on their servers. It will be nice to have Plex built-in. 

https://hub.docker.com/r/plexinc/pms-docker/

**Comment by frenck** [comment]
Thank you for this suggestion!

**Comment by Pwyll28** [comment]
I'm interested too :D

**Comment by frenck** [comment]
This add-on is currently being developed.
In case you are interested in testing the development version, add the `edge` add-on repository to your Hass.io installation.

`https://github.com/hassio-addons/repository-edge`

**Comment by frenck** [comment]
The Plex Media Server add-on has been created and published.
It is now generally available via the well-known repositories.
