### ISSUE TITLE
❇ TensorFlow

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/repository#36]
# Problem/Motivation
TensorFlow is a popular machine learning library, with applications including [image recognition](https://www.tensorflow.org/tutorials/image_recognition) which have [applications in HA](https://community.home-assistant.io/t/tensorflow-camera-door-sensor/28891/7).  However installation is very slow (15 mins), and a docker 1 click add-on would be much more convenient and probably improve performance. It would also be nice if there were a way to add community selected classifiers that could then be used by a HA component.

# References
https://www.tensorflow.org
https://github.com/lhelontra/tensorflow-on-arm/releases/tag/v1.3.1
https://community.home-assistant.io/t/tensorflow-camera-door-sensor/28891/7

**Comment by frenck** [comment]
Thx m8!

**Comment by DanielXYZ2000** [comment]
Sounds very interesting. Consider automations based on the recorded sensor and actor data.
