### ISSUE TITLE
Publish action failed & not retried

### ISSUE THREAD

**Issue by mundschenk-at** [hassio-addons/repository#365]
# Problem/Motivation

The publish action after the recent release of zwavejs2mqtt 0.32.2 failed (probably due to GH issues at the time). While the release action itself was restarted and eventually succeeded, the publish workflows here and in the beta repository have not been restarted.

## Proposed changes

The action should be manually restarted to publish the new release of the addon.

**Comment by frenck** [comment]
Wrong repo.

**Comment by mundschenk-at** [comment]
What would be the right repo, @frenck? The specific add-on?
