### ISSUE TITLE
❇ Airsonos

### ISSUE THREAD

**Issue by james-fry** [hassio-addons/repository#37]
# Problem/Motivation
Airsonos is an airplay-Sonos bridge that exposes Sonos speakers as airplay targets.
It addresses a much hated deficiency in the Sonos ecosystem that it's not possibly to send audio to a Sonos speaker.

# References
https://github.com/stephen/airsonos
https://hub.docker.com/r/justintime/airsonos/

**Comment by frenck** [comment]
Awesome! Thx!

**Comment by gieljnssns** [comment]
Can't you use this? https://github.com/philippe44/AirConnect

**Comment by frenck** [comment]
Already on it... Add-on is in the process of being released.

**Comment by frenck** [comment]
Released: https://github.com/hassio-addons/addon-airsonos
