### ISSUE TITLE
❇ Pydio

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/repository#38]
# Problem/Motivation
[Pydio](https://pydio.com/) is like Google Drive for your personal content. You can get access to it from anywhere in the world, give people accounts to access your content, or share a folder to anyone with a public link. For users who aren't comfortable with Github, those who dont expose their HA instance to the internet, or just as a convenience for sharing files on the HA forum, this could be a really useful resource. There are also iOS/android/desktop apps so checking e.g. videos captured via a HA component, would be pretty straightforward using the app. 

# References
https://pydio.com/
http://demo.pyd.io/
https://hub.docker.com/r/jordancrawford/rpi-pydio-docker/
https://github.com/pydio/pydio-sdk-python
https://itunes.apple.com/gb/app/pydio-pro/id1109419882?mt=8

**Comment by frenck** [comment]
Nice! Thanks

**Comment by frenck** [comment]
Why close this? This is still a nice idea?
