### ISSUE TITLE
 Add PhotoPrism add-on

### ISSUE THREAD

**Issue by vmartinv** [hassio-addons/repository#381]
# Motivation

PhotoPrism® is an AI-powered app for browsing, organizing & sharing your photo collection. It makes use of the latest technologies to tag and find pictures automatically without getting in your way. 

https://github.com/photoprism/photoprism

![PhotoPrism UI](https://camo.githubusercontent.com/5e03a87e47aad26ad7248b8b43eac6471fe96f7b655ac2e532697692753c3ff8/68747470733a2f2f646c2e70686f746f707269736d2e6170702f696d672f75692f6465736b746f702d3130303070782e6a7067)

## Proposed changes

- The app is already dockerized (docker-compose), they won't drop support.
- It should read the data from share/ or a specified directory

> Then I would suggest you look at creating it, note this project isn't taking any new submissions for new addons.
> 
> I believe this should likely be converted to a discussion.

You're right I will create a discussion

**Comment by sinclairpaul** [comment]
I would doubt this would be a good fit for running under the supervisor (it's using Tensorflow), as the resource requirements would be pretty high on a Pi/SBC running other components.

**Comment by vmartinv** [comment]
> I would doubt this would be a good fit for running under the supervisor (it's using Tensorflow), as the resource requirements would be pretty high on a Pi/SBC running other components.

I disagree, Tensorflow and raw image conversion can be disabled from the UI/config while still keeping the rest. Furthermore if the system has less than 1GB RAM it will be [automatically disabled](https://docs.photoprism.app/getting-started/#system-requirements).

**Comment by sinclairpaul** [comment]
Then I would suggest you look at creating it, note this project isn't taking any new submissions for new addons.

I believe this should likely be converted to a discussion.

**Comment by vmartinv** [comment]
You're right, I created #382
