### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/repository#40]
# Problem/Motivation
For remote access to the database, [MySQL is a good solution](https://community.home-assistant.io/t/setting-up-mysql-on-a-synology-nas-docker-container/16253). Initially investigated this as InfluxDB didn't appear to be accurately capturing all of the data from my db. 

# References
https://hub.docker.com/r/hypriot/rpi-mysql/

**Comment by frenck** [comment]
The core team does offer MariaDB (MySQL drop-in replacement). Isn't that enough?

**Comment by robmarkcole** [comment]
Yes thats true. Cheers!
