### ISSUE TITLE
❇ Simple Bluetooth Speaker Media player for TTS announcements 

### ISSUE THREAD

**Issue by tatunts** [hassio-addons/repository#41]
# Problem/Motivation

Hey there! I would like to suggest an addon, if possible: It would be great to have a simple component that uses the built in bluetooth radio on the Pi3 to connect to a bluetooth speaker and use it as a simple TTS announcer for your home/office. I was reading about using mopidy and had no luck with it. Thanks!

# Refs

https://community.home-assistant.io/t/tts-on-bluetooth-speaker-via-raspberry-pi/21276

**Comment by frenck** [comment]
That is a rather broad/loose specification, but ok... I do like the idea.

Will add it.

**Comment by adipose** [comment]
> 
> 
> > The lack of movement on this for the last year suggests it's not much of a priority to get it working natively, either.
> 
> This is the Community add-ons project, which is driven by the community. So someone with spare time, the use case and the knowledge has to find the will to donate his time towards this.
> 
> There is no such thing as priorities.

Understood.  Allow me to rephrase: "No one is working on this."  The last comment on the thread ("will add it") suggested that maybe it was being worked on, but given the amount of time elapsed, I'm guessing it wasn't.

I attempted for 2 days, at which point I concluded the design of hass.io/homeassistant does not lend itself to this feature.  Homeassistant can support this but it's difficult with the docker/hypervisor setup of hass.io.

I'm happy to lend my help to making this work, as I'm a software designer and a tinkerer, but I would need some help figuring out how to give the docker proper access to the bluetooth stack.

**Comment by frenck** [comment]
Hmmm, I see why you thought I was working on this. My reaction was incomplete / not so well picked.

"Added to the list" would be a better choice of words.

**Comment by magiva** [comment]
so if this is working on hassbian, isnt it possible with hassio, just needs the same doing to the parent system as has been done to hassbian ? 

this would be such an easy and perfect solution for annoucements, alarms, door bells etc

**Comment by frenck** [comment]
@ Home Assistant there are currently new audio capabilities developed, which might include these capabilities in the near future.

From an add-on perspective, this would be hard to implement.

Nevertheless, thanks for the suggestion!
