### ISSUE TITLE
SSH & Web Terminal > Init_Commands > YAML ">-" forced into "|-"

### ISSUE THREAD

**Issue by erwin** [hassio-addons/repository#419]
# Problem/Motivation

I would like to use multiple lines for YAML for my init_commands and just have those lines merged automatically without whitespace.

YAML supports this with the `>-` (merge all lines without newlines, don't add trailing newline).

For example, I would like to do something like:

```
init_commands:
  - >-
    autossh -M 18123 
      -o 'StrictHostKeyChecking=no' -oControlMaster=yes
      -oControlPath=/config/ha.sock 
      -N -f -p 333 'user@host'

```

## Expected behavior

I would like the `- >-` to be preserved, and thus when the YAML engine reads in the content, the intervening newlines would be ignored.

## Actual behavior

The web GUI is converting the `- >-` to `- |-` (meaning all newlines will be preserved)

```
init_commands:
  - |-
    autossh -M 18123 
      -o 'StrictHostKeyChecking=no' -oControlMaster=yes
      -oControlPath=/config/ssh_keys/ha.sock 
      -N -f -p 333 'user@host'
```

Also, I tried to add `\` at the end of each line.
Also tried escaping the \... `\\`
And even `\\\` at the end of each line, but none of those would work for me.

If you actually know what your command is instead of blindly pasting in someone else's stuff, it's very helpful to have embedded line-breaks - thus every shell I've ever seen supports it :-)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Some option for preserving the `>-` YAML formatting so that multi-line commands are easier to enter and edit.

Took me a while to figure out `init_commands` only was available with this version of HA SSH, not the default one.

Thanks so much for making this. My apologies if this note felt disrespectful. I know it's a huge amount of effort to make this stuff.

Thanks for taking the time to read this.

**Comment by frenck** [comment]
This is not something the add-ons can do anything about. Please report your issue with the Home Assistant project. Thanks 👍
