### ISSUE TITLE
❇ Google Cloud Print Connector

### ISSUE THREAD

**Issue by kevingrubbs** [hassio-addons/repository#42]
An add-on that allows HASS to be a google cloud print connector to serve local printers would be awesome! I believe it would require the [CUPS add-on](https://github.com/hassio-addons/repository/issues/33) to be implemented first, but once that is done integrating this would be super cool!
https://github.com/google/cloud-print-connector

**Comment by frenck** [comment]
Nice idea! Thank you for your suggestion.

**Comment by pattyland** [comment]
Google Cloud Print is discontinued at the end of this year: https://support.google.com/chrome/a/answer/9633006 :(
