### ISSUE TITLE
❇ MySensors Gateway

### ISSUE THREAD

**Issue by zgsm1234** [hassio-addons/repository#43]
# Problem/Motivation

I would like to suggest an addon, if possible: previously using Home Assistant via the Hassbian installation on RPI3,  a Mysensors gateway could be installed via SSH ([https://www.mysensors.org/build/raspberry](url)). Running Hassio means now unable to install the Mysensors code in the usual way, and I think this needs to be done via an add-on on Hassio from reading some of the topics on it. Thanks in advance.

**Comment by frenck** [comment]
Thank you for your suggestion!

**Comment by pezmannen** [comment]
Also very interested in this. Currently running my gateway on my Raspberry but would like to switch over to hass.io

**Comment by tytuseek** [comment]
That is the key feature for me. All lights at my home (except 2 bulbs) are controlled by mysensors gateway. I hope it will be released really soon. Can't wait!

**Comment by swcrawford1** [comment]
This is a key feature for me as well

**Comment by gieljnssns** [comment]
Any updates on this?

**Comment by frenck** [comment]
This repository contains a "whish-list" of add-ons, and there are a lot. At this moment, this add-on is still just an "idea".

**Comment by gohassgo** [comment]
Since we're wishing here, if like to see support for all three gateway types--serial, Ethernet and MQTT.

Have you seen this? It's close to working with MQTT. Sounds like it works with docker and Hass but just not as an add-on. Maybe you could give this guy a hand...

https://forum.mysensors.org/topic/8877/gateway-addon-for-hass-io
https://github.com/ghiglie/hassio-addons

**Comment by frenck** [comment]
@gohassgo That is off-topic. If you'd like different/new add-on, please create a separate GitHub issue. Thank you.

**Comment by gohassgo** [comment]
How so? This guy is trying to build a MySensors Gateway add-on and it is so very close to working!

**Comment by frenck** [comment]
I'm sorry, misunderstood your comment. Thx for letting us know in that case 👍

**Comment by gohassgo** [comment]
And there's this!

https://community.home-assistant.io/t/mysensors-mqtt-gateway-integration/39743

**Comment by lettore** [comment]
I tried to make a working addon but it seems impossible to connect succesfully to the radio.
It seems that needs to connect to dev/spidev0.0 but the image is missing that, and if i mount dev/spidev0.0 from the system it only says that it can't connect to the radio.
I should say that i'm really noob with docker, but there are so many addons that uses the GPIO that i can't understand what is wrong.
This is the config file (i'm trying to modify the Ghiglie addon that is not working for me);

{
  "name": "MySensors Gateway",
  "version": "0.14",
  "slug": "mysgw",
  "description": "MySensors Gateway Add-on",
  "url": "https://github.com/ghiglie/hassio-addons/addon-mysgw",
  "arch": [
      "amd64",
	  "i386",
      "armhf"
  ],
  "startup": "before",
  "boot": "auto",
  "devices": [ 
       "/dev/mem:/dev/mem:rw",
       "/dev/spidev0.0:/dev/spidev0.0:rw"
  ],
  "privileged": [ "SYS_RAWIO", "SYS_ADMIN", "NET_ADMIN" ],
  "full_access": true,
  "gpio": "true",
  "apparmor": "false",
  "ports": {
    "5003/tcp": 5003
  },
  "options": {
    "log_level": "info",
	"type": "mqtt",
	"mqtt_server": "addon_core_mosquitto.hassio",
	"transport": "rf24", 
	"mqtt_clientid": "mygatewayp",
	"mqtt_topicin": "mysensors-in",
	"mqtt_topicout": "mysensors-out"
  },
  "schema": {
    "log_level": "match(^(trace|debug|info|notice|warning|error|fatal)$)",
    "type": "match(^(none|ethernet|mqtt)$)",
	"mqtt_server": "str",
	"transport": "match(^(none|rf24|rs485|rfm95|rfm69)$)", 
	"mqtt_clientid": "str",
	"mqtt_topicin": "str",
	"mqtt_topicout": "str"
  },
  "environment": {
    "LOG_FORMAT": "{LEVEL}: {MESSAGE}"
  }
}
Someone can help?

**Comment by frenck** [comment]
@lettore This is not a support forum. Thanks.
