### ISSUE TITLE
Uptime Kuma v0.3.1 not being pulled by auto release

### ISSUE THREAD

**Issue by OneYellowLemon** [hassio-addons/repository#448]
# Problem/Motivation
[Uptime Kuma v0.3.1](https://github.com/hassio-addons/addon-uptime-kuma/releases/tag/v0.3.1) was released four days ago, but has not been picked up by the repository updater.

## Expected behavior
`addonsbot` to release the new version in this repository

## Actual behavior
v0.3.0 is still the latest version available from this repository (5babaf014de1f74ae392c302246d309cec8217f8).

## Proposed changes
Make `addonsbot` automatically update the addon, or release v0.3.1 manually

**Comment by frenck** [comment]
Fixed, also released v0.3.2.

Thanks for reporting 👍 

../Frenck
