### ISSUE TITLE
new add-on suggestion for using usb instead of Sd for DB and Logfiles

### ISSUE THREAD

**Issue by hvbhome** [hassio-addons/repository#45]
# Problem/Motivation
I would like to suggest an addon, if at all possible: 
Reading and writing the Hassio Db and log files, and probably other files, to the SD card seems to be sub-optimal when using a Pi, as i am. Wearing the SD more than needed, and also interfering with other administrative tasks the Pi is taking care of at the same time.
Especially when many records have to be written. In my case, i have rather a lot of mqtt sensors being recorded. 
Next to that the DB is growing larger by the hour.... 

All the more reason to try and mitigate these 'issues' by moving the db files to an attached usb drive, or some other network destination. Have a dedicated place for these files would also enable the main install to stay as clean as can be.

This seems to be possible but it not something for the uninitiated. It is not very well documented, if at all.
It would be very very nice if a Hassio Add-on could take the user by the hand, recognize usb drives, and available Network locations, and consequently have these files moved there.

Hope anything close would be possible
 Many thanks in advance!
Cheers,
Marius
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
I do like the idea, nevertheless, this would be hard to do in an add-on.
E.g., one of the problems would be actually mounting the USB drive in the add-on.

This should be added as a feature to Hass.io / Home Assistant itself to fix is properly.
