### ISSUE TITLE
Lightware Proxy Addon.

### ISSUE THREAD

**Issue by ColinRobbins** [hassio-addons/repository#455]
# Problem/Motivation

I have migrated from HA Core / penv to running under HA Operating System, on a Raspberry PI.

On my penv PI config, I used the run a proxy for Lightwave alongside HA, using
https://github.com/ColinRobbins/Homeassistant-Lightwave-TRV

I am now trying to turn this into an add-on.
The addon is running the proxy OK, but I have hit an issue.

The Proxy and HA  Lightwave Integration (https://www.home-assistant.io/integrations/lightwave/) need to use the same network addess, due to the way this works with Lightwave.
In the penv model, this is fine, as the proxy and integation use SO_REUSEADDR.

But under docker, it seems SO_REUSEADDR is not supported.    So I get address in use errors.

I'm looking for suggestions on how to workaround this (apart from running the proxy on a seperate computer, which is my current soluion).

## Expected behavior

It all works on the smae machine, as it did under a penv

## Actual behavior

I get address in use errors.

## Steps to reproduce

As above.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there @ColinRobbins 👋 

I don't have the right answer for you on this matter, as in, for resolving the use of SO_REUSEADDR.

That said, looking at the code upstream, this shouldn't be an add-on IMHO; this could be a direct integration.

I'm going to close the issue on this end, as this is not an issue with our community add-ons.

../Frenck
