### ISSUE TITLE
❇ Hyperion

### ISSUE THREAD

**Issue by begicj** [hassio-addons/repository#46]
It would be nice to have Hyperion server in hass.io

https://github.com/hyperion-project/hyperion/issues

**Comment by frenck** [comment]
Ref: hyperion-project/hyperion#771

**Comment by LuckyTNT** [comment]
Just make sure not to go with Hyperion but Hyperion.NG
It is said to be beta but it is pretty much completely remade and much better and stable project.
https://github.com/hyperion-project/hyperion.ng
