### ISSUE TITLE
VSCode add-on cannot be controlled with mouse or arrow keys in Swift Mac app

### ISSUE THREAD

**Issue by Bartcardi** [hassio-addons/repository#466]
# Problem/Motivation

> When I use the home assistant swift mac app I cannot scroll within any vscode panel, nor can I control the cursor with my arrow keys. 

## Expected behavior

> Normal mouse and arrow key behaviour inside active vscode panels.

## Actual behavior

> When I scroll with my trackpad the complete vscode panel gets lifted up or pushed downward. When I use my arrow keys the cursor doesn't move.

![HA_VS_Code](https://user-images.githubusercontent.com/11993543/213002531-05e1693f-c072-4335-aaf6-539c57302cca.gif)

## Steps to reproduce

> Install the mac app and initialise vscode add-on.

## Proposed changes

> I don't have a workaround.

**Comment by frenck** [comment]
There is not much I can do about that 🤷 
Please report the issue with the app you are using.

../Frenck

**Comment by Bartcardi** [comment]
Ok fair enough. I will raise the issue with the swift app builders.
