### ISSUE TITLE
Auto Backup configuration files

### ISSUE THREAD

**Issue by kolossboss** [hassio-addons/repository#47]
# Problem/Motivation

I would like to see an addon to auto backup the configuration files.

Ideas:

-  to a smb/ftp/afp network share
-  to a cloud service (google drive, dropbox ...)
-  to an USB drive
-  versions 
-  configured triggers like time or after a restart of HA or via an automation

Maybe using [duplicity](http://duplicity.nongnu.org/) or [Rsnapshot](http://rsnapshot.org/)

**Comment by frenck** [comment]
Maybe this will be sufficient? #29 ?

**Comment by kolossboss** [comment]
Oh sorry I overlooked that.

**Comment by frenck** [comment]
It's ok m8 👍
