### ISSUE TITLE
[grocy addon] save button, in chore form doesn't work

### ISSUE THREAD

**Issue by felipemfa** [hassio-addons/repository#474]
# Problem/Motivation

When I try add a new chore (any parameters) and click the "save" button

## Expected behavior

Message success and save chore.

## Actual behavior

Nothing

## Steps to reproduce

Manage master data -> Chores -> Add -> fill any data -> click in save button

I can see error only in chrome console:

![image](https://user-images.githubusercontent.com/2481536/220640729-2e07df92-baee-487e-bfc8-89473dd4618e.png)
about grocy in my system:

Version 3.3.2
Released on 2022-11-12 3 months ago

PHP Version 8.0.25
SQLite Version 3.38.5

**Comment by frenck** [comment]
This is not the right issue tracker. Please refer to the documentation of the add-on.

Thanks 👍 

../Frenck
