### ISSUE TITLE
'StoreManager.add_repository' blocked from execution, no supervisor internet connection

### ISSUE THREAD

**Issue by MuhammadYacoub** [hassio-addons/repository#476]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not an issue of this repository.

Sounds like you have issues with the Supervisor, which is not something this repository handles.

../Frenck
