### ISSUE TITLE
Canoot see "Home Assistant Community Add-ons" section

### ISSUE THREAD

**Issue by algovera** [hassio-addons/repository#495]
# Problem/Motivation

Canoot see "Home Assistant Community Add-ons" section in Add-on Store
However I am able to see "Official add-ons"

When I tried adding by URL "https://github.com/hassio-addons/repository"
I get an error "Can't add https://github.com/hassio-addons/repository, already in the store"

## Expected behavior
See "Home Assistant Community Add-ons" section in Add-on Store

## Actual behavior

Cannot see "Home Assistant Community Add-ons" section in Add-on Store

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

Additional Info - just upgraded to new supervisor and did not help
Home Assistant 2023.3.6
Supervisor 2023.04.1
Frontend 20230309.1 - latest

**Comment by mrDal666** [comment]
Same problem here

**Comment by frenck** [comment]
Anything in the Supervisor logs?

**Comment by algovera** [comment]
when i tried adding the repository, this error message is shown in log
23-05-09 13:51:04 ERROR (MainThread) [supervisor.store] Can't add https://github.com/hassio-addons/repository, already in the store

which is the same as what's shown in the frontend
![image](https://user-images.githubusercontent.com/48702353/237006324-a32925ef-b8af-4988-9ffa-185feeb011cd.png)


however, still nothing in the frontend
![image](https://user-images.githubusercontent.com/48702353/237006237-6d3b1623-1710-4c61-b413-2d245c3d7176.png)

**Comment by frenck** [comment]
> when i tried adding the repository, this error message is shown in log

Yes, you said that already in your original post. The question was: Do you see anything in the logs?

**Comment by algovera** [comment]
that's all there is, an identical error message

23-05-09 16:54:40 ERROR (MainThread) [supervisor.store] Can't add https://github.com/hassio-addons/repository, already in the store

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/48702353/237046246-e1496483-9345-49b3-ad12-46d09c3255e0.png">

**Comment by algovera** [comment]
Here is the log on refresh

![image](https://github.com/hassio-addons/repository/assets/48702353/1af33203-b2f7-4127-8b2c-cb85aae0f93e)


does  `/data/addons/git/a0d7b954` provide any clue

**Comment by frenck** [comment]
That is an Home Assistant Supervisor issue, which I cannot do anything about from an add-on repository.

You could try to run the `ha supervisor repair` command from an terminal to see if it is able to repair it; if not, I would recommend filing an issue with the Home Assistant Supervisor project.

../Frenck

**Comment by superkco** [comment]
I have same issue using Home Assistant OS and restoring some addons from a backup. I have tryed also ha supervisor repair command but still having the same problem:

![image](https://github.com/hassio-addons/repository/assets/59687496/b1836d75-2e48-4dc9-ae0a-b22ac8772b47)

![image](https://github.com/hassio-addons/repository/assets/59687496/265a7ac8-16c0-4b6a-a3ce-13e7b92744a5)

**Comment by frenck** [comment]
> I have same issue using Home Assistant OS and restoring some addons from a backup. I have tryed also ha supervisor repair command but still having the same problem:


Sorry to hear that, see my previous comment to see what to do. There is nothing I can do from this end.

Sorry.

../Frenck

**Comment by superkco** [comment]
Well now works again, I haven't found my problem but maybe, as I have repaced my old equipment by a new one, including the Server DHCP addon, something wasn't refreshed and after a few hours everithing workd again!

**Comment by superkco** [comment]
Hi, sorry for the late reply,

I found the problem, It was with some devices using the "Local Tuya"
integration. If I disabled it, everything works fine.

Regards.

**Comment by fwartner** [comment]
Still facing this issue..
I reinstalled Home Assistant and restored using a backup..

The repository seems to be installed but isnt available to install any addons.
