### ISSUE TITLE
netbird addon

### ISSUE THREAD

**Issue by lfarkas** [hassio-addons/repository#498]
Create a NetBird addon

**Comment by frenck** [comment]
This is not an issue 😉 

Yet, I have no plan in creating a NetBird add-on any time soon. The biggest issue with NetBird is the lack of mobile clients IMHO.

../Frenck

**Comment by lfarkas** [comment]
there is a mobile client but it's currently in beta and not yet public although the core already in the master (see eg: https://github.com/netbirdio/netbird/commit/e096ec39d570f51b1c5cd771163f86b674736cb2)
