### ISSUE TITLE
❇Passbolt open source password manager

### ISSUE THREAD

**Issue by gieljnssns** [hassio-addons/repository#50]
Passbolt: The password manager your team was waiting for. Free, open source, self-hosted, extensible, OpenPGP based.
If you can make an addon, hassio could be the server for storing al your passwords.

https://www.passbolt.com
https://www.passbolt.com/help/tech/install
https://github.com/passbolt/passbolt_api

**Comment by frenck** [comment]
We currently provide Bitwarren as an alternative. I'm not planning on adding a multiple of the same applications in our catalog, as there is many more things we could do.

Nevertheless, thanks for your suggestion.
