### ISSUE TITLE
❇ Netdata 

### ISSUE THREAD

**Issue by gieljnssns** [hassio-addons/repository#54]
# Problem/Motivation

> Unparalleled insights, in real-time, of everything happening on your systems and applications, with stunning, interactive web dashboards and powerful performance and health alarms.

https://my-netdata.io
https://github.com/firehol/netdata

**Comment by frenck** [comment]
Thank you for suggesting a new add-on @gieljnssns.

Nevertheless, due to the nature/security of Hass.io, this add-on would not work.
Hass.io does not allow add-ons full access to the underlying system and/or Docker sockets, which makes this add-on impossible.

Sorry!

**Comment by frenck** [comment]
Re-opened this one... got some ideas on getting this working now.

**Comment by frenck** [comment]
OK, so those ideas failed. Closing this, I've now learned as an add-on this would be impossible for a long time 👎
