### ISSUE TITLE
Adding contributors section and github stats to Readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [hassio-addons/repository#543]
# There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
Any contributions make are greatly appreciated, for that we need to add new section for contributors and adding to the readme file!

![contributors](https://github.com/hassio-addons/repository/assets/147402107/be42467f-3503-43ab-b459-65e15002df6a)

**Comment by Kalyanimhala** [comment]
@frenck kindly assign me this #543 issue I want to work on it.

**Comment by frenck** [comment]
This is a generated respository. That makes no sense.
