### ISSUE TITLE
❇Tautulli (PlexPy)

### ISSUE THREAD

**Issue by kolossboss** [hassio-addons/repository#55]
An Tautulli (PlexPy) Addon would be nice.
I think there is already an official Docker container.

[Tautulli (PlexPy)](http://tautulli.com/#heading)
[Tautulli Github](https://github.com/Tautulli/Tautulli)
[Tautulli Docker](https://hub.docker.com/r/tautulli/tautulli/)
[Tautulli Installtion](https://github.com/Tautulli/Tautulli-Wiki/wiki/Installation)

**Comment by dpeluso** [comment]
+1 I'd also like to see this add-on

**Comment by manix84** [comment]
+1 - yes please.

**Comment by motoolfan** [comment]
Hell Yes!!  Thanks!

**Comment by frenck** [comment]
Changed status to Accepted: Will be made.

**Comment by ArnoutVerbeken** [comment]
Don't know if it helps, but Tautulli now supports "webhook" also as a notification agent.  I think it is the most easy way to implement.

**Comment by frenck** [comment]
@ArnoutVerbeken The add-on has been implemented and is expected to be released into the public today.

**Comment by ludeeus** [comment]
This add-on is now released 🎉
