### ISSUE TITLE
Adding Homeway To The Community Add-On Repo

### ISSUE THREAD

**Issue by QuinnDamerell** [hassio-addons/repository#558]
Hello! 

I'm a member of the Home Assistant community who fell in love with the Home Assistant project and wrote an add-on! I have a background in software and services, so I wanted to contribute to the community by building a service that offers free (but limited) remote access for Home Assistant! I have the service and add-on ready in a beta release. I have yet to release it broadly; just a small group of about 100 users are helping me test it.

Here's a link to the add-on:
https://github.com/homewayio/AddOn

Since my goal is to make something beneficial for the community, I want to add it to HA community add-on repo. I'm 100% behind the add-on and am trying to make it the best it can be. I'm following all of the best practices for add-ons, like building docker images and pushing them to GitHub for installation, enabling app armor, reducing the risk surface area, etc.

Let me know if there's anything else I need to do to be eligible for the community add-on repo. I'm happy to take suggestions, requirements, or work with anyone on making my add-on community repo worthy!

I noticed that most of the community add-ons exist in this hassio-addons GitHub org. Is that a requirement? Or can my add-on exist in my GitHub org? I'm fine either way; I'm just wondering. :)

**Comment by tjorim** [comment]
We are currently not accepting third party add-ons to this repository.

https://github.com/hassio-addons/repository?tab=readme-ov-file#adding-a-new-add-on

**Comment by frenck** [comment]
As pointed out by Jorim above, we currently do not accept new add-ons to this repository.

../Frenck

**Comment by QuinnDamerell** [comment]
Ah, thank you, I didn’t realize that. Is there any possibility of me becoming a community developer so I can contribute this and other addons?

**Comment by tjorim** [comment]
You can always contribute to the current add-ons in this repo by opening a PR (in the appropriate add-on repo). No new add-ons will be added. Users are free to simply add your own repo to their add-on store.

**Comment by QuinnDamerell** [comment]
Awesome thank you! As I use the addons I will certainly keep an eye out for any issues and fix them if possible! Thank you for you efforts!
