### ISSUE TITLE
❇Traccar

### ISSUE THREAD

**Issue by Cooper-Dale** [hassio-addons/repository#56]
Traccar Server - GPS Tracking Software - Free and Open Source System - Support for more than 140 GPS protocols and more than 1000 models of GPS tracking devices. -  [traccar.org](https://www.traccar.org/)
The Docker image is already there - [Traccar on Github - docker ](https://github.com/tananaev/traccar/tree/master/setup/docker)

Before migrating to Hass.io the Traccar was running on my pi and it was reporting to HA via platform: **gpslogger**
URL in traccar config:  `https://ema.ple/api/gpslogger?latitude={latitude}&amp;longitude={longitude}&amp;device={uniqueId}&amp;speed={speed}&amp;direction={course}&amp;provider=Traccar&amp;api_password=pass `

Others and I will be wery happy to see this addon here in Hass.io. Thank you

**Comment by frenck** [comment]
Addon has been created and release.

https://github.com/hassio-addons/addon-traccar

**Comment by ludeeus** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:
