### ISSUE TITLE
Prometheus addon discontionued?

### ISSUE THREAD

**Issue by gbbirkisson** [hassio-addons/repository#584]
# Problem/Motivation

> (Why the issue was filed)

I see that the [prometheus addon](https://github.com/hassio-addons/addon-prometheus) was archived in the beginning of 2024. I cannot find a reason why, and I cannot find it anywhere else (not in beta, or edge repo either).

Any insights into this? Is the addon discontinued, if so, why?

## Expected behavior

> (What you expected to happen)

N/A

## Actual behavior

> (What actually happened)

N/A

## Steps to reproduce

> (How can someone else make/see it happen)

N/A

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

N/A

**Comment by tjorim** [comment]
It was never released, just for testing and now indeed archived/discontinued. There was probably low usage (never made it to stable so makes sense) and lack of time or resources. Source is still available so you could fork the repo and make adjustments needed.

**Comment by gbbirkisson** [comment]
Thanks, ended up rolling my own version: https://github.com/gbbirkisson/hass-repo/tree/master/prometheus
