### ISSUE TITLE
❇HA Open Zwave Connection Map

### ISSUE THREAD

**Issue by magnusoverli** [hassio-addons/repository#59]
# Problem/Motivation
I used to run z-way (https://z-wave.me/z-way/) to communicate with my zwave devices, and this tool had the ability to display a map of the zwave mesh topology. This is a very useful tool to better understand the workings of zwave and to do propper troubleshooting when something fails.
This functionality already exists, using an external tool: https://github.com/magma1447/HomeAssistant-Zwave-ConnectionMap
It simply takes OZW_Log.txt and zwcfg_xxxxx.xml files and creates a map using Graphviz (https://www.graphviz.org).

It would be awesome and very very useful if this could be made into an add-on for hassio!

**Comment by frenck** [comment]
I've been reconsidering the open suggestions.
This one has been open a long time, and didn't receive any other support as well.
With the upcoming changes to Z-Wave for Home Assistant, the future look bright!

So, I'll go ahead and close this up.

Thanks for your suggestion!
