### ISSUE TITLE
404 Client Error: Not Found

### ISSUE THREAD

**Issue by sgong4** [hassio-addons/repository#60]
i try to  install samba,but i don't work. i check the system log : samba can't install. what should i do to fix the problem. thanks. 

[hassio.docker.interface] Can't install homeassistant/armhf-addon-samba:3.0 -> 404 Client Error: Not Found ("no such image: homeassistant/armhf-addon-samba:3.0: No such image: homeassistant/armhf-addon-samba:3.0").

**Comment by frenck** [comment]
Hi there @sgong4,

Thank you for your error report, nevertheless, the Samba add-on is not a Community add-on, it is a core add-on. You should go to https://github.com/home-assistant/hassio-addons.

Sorry m8!
