### ISSUE TITLE
How to install Grafana as Add-on in HA Container

### ISSUE THREAD

**Issue by NicolasGoeddel** [hassio-addons/repository#604]
# Problem/Motivation

I run HA Container using docker compose and there is no Add-On store where I could just install Grafana with one click.

## Expected behavior

There is a documentation that shows how to install it for every HA flavor.

## Actual behavior

I don't know how to integrate Grafana.

## Proposed changes

Add a step-by-step guide about how to install Grafana or any other add-on manually without the need of a Supervisor or similar.

**Comment by frenck** [comment]
> and there is no Add-On store where I could just install Grafana with one click.

Correct, you manage your own Docker environment 🤷 

> There is a documentation that shows how to install it for every HA flavor.

There is no relationship with Home Assistant this case. 

> I don't know how to integrate Grafana.

There is no integration for Grafana in Home Assistant.

> Add a step-by-step guide about how to install Grafana or

Consult the Grafana documentation?

> or any other add-on manually without the need of a Supervisor or similar.

That makes no sense at all. You manage your own setup, consult the documentation of the software you wish to install in your Docker environment for these cases.

If this imposes questions for you, you are likely running an set up that maybe not fitting for you (I don't mean this one offensive, but just something you might want to re-consider in this case).

Closing this issue, as this not an add-on issue at all.

../Frenck
