### ISSUE TITLE
Hassio API

### ISSUE THREAD

**Issue by slavendam** [hassio-addons/repository#609]
Hi,
this is not bug in your hassion-addons repo, but just question.

I've created add-on which is run in "web UI" in HA. 
Problem is that with first login to HA, hassion session is not generated and add-on can not use hassio API, I'm getting error 401 in card on dashboard. First we need to directly open add-on from side bar/add-on list, and than can use it from Home dashboard as a card.
Here I explained problem with more details: https://github.com/home-assistant/supervisor/issues/5045

My question is did you have similar problem with some of add-ons which uses web UI, and how did you solve it to automatically generate hassio ingress session on login to HA?

Thanks!

**Comment by frenck** [comment]
This is a known "problem" with the Home Assistant frontend. This also occurs if you'd embed graphs from Grafana into your Home Assistant dashboard.

Closing here, as this is not something this project can do anything about.

../Frenck
