### ISSUE TITLE
❇ Room Assistant

### ISSUE THREAD

**Issue by IzzyWizzy666** [hassio-addons/repository#61]
# Problem/Motivation

https://github.com/mKeRix/room-assistant

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<blockquote><img src="https://avatars2.githubusercontent.com/u/770596?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/mKeRix/room-assistant">mKeRix/room-assistant</a></strong></div><div>room-assistant - A companion client for Home Assistant to handle sensors in multiple rooms.</div></blockquote>

**Comment by frenck** [comment]
Thank you!

**Comment by iantrich** [comment]
Someone has released a Room Assistant add-on: https://community.home-assistant.io/t/hass-io-add-on-room-assistant/59774

**Comment by frenck** [comment]
Yep, nevertheless, we might get it added to the community repo.
or try to implement a more standardized version fitting this projects flow.

**Comment by frenck** [comment]
The maintainer of room assistant also maintains the add-on, lets us close this one.
