### ISSUE TITLE
❇ Alarm Decoder Webapp

### ISSUE THREAD

**Issue by SP410** [hassio-addons/repository#63]
# Problem/Motivation
Home Assistant currently interfaces with Alarm Decoder devices through the alarm decoder hub.  However, the hub only uses a fraction of Alarm Decoder's capabilities.  NuTech provides an Alarm Decoder Webapp docker image that allows for keypad emulation, and firmware upgrades of the alarm decoder device.  

Proposal:
Use https://github.com/tenstartups/alarmdecoder-webapp as a template to create a HassIO addon.  

<blockquote><img src="https://avatars1.githubusercontent.com/u/8996915?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/tenstartups/alarmdecoder-webapp">tenstartups/alarmdecoder-webapp</a></strong></div><div>alarmdecoder-webapp - Docker image for the Nutech alarmdecoder Python web application.</div></blockquote>

https://www.home-assistant.io/components/alarmdecoder/

**Comment by SP410** [comment]
https://github.com/nutechsoftware/alarmdecoder-webapp

**Comment by frenck** [comment]
Thank you for your suggestion!

**Comment by frenck** [comment]
We should extend the alarm decoder in Home Assistant for these kinds of things.
Since I do not own this product, and nobody stood up to create it since 2018, I'll go ahead and close this suggestion.

Nevertheless, thanks for providing a suggestion!
