### ISSUE TITLE
Grafana does not keep database connector plugins between restarts

### ISSUE THREAD

**Issue by sigxcpu76** [hassio-addons/repository#639]
# Problem/Motivation

> No retention for datasources (I tried database connector for ClickHouse) between restarts

## Expected behavior

> Keep the plugins after restart

## Actual behavior

> ClickHouse plugin missing. Need to reinstall on each restart

## Steps to reproduce

> Install  ClickHouse database connector and then restart HASS OS

## Proposed changes

> Mount `/var/lib/grafana/plugins` inside the container to an external persistent storage.

**Comment by sinclairpaul** [comment]
Although this isn't the correct repo to log the issue, I would suggest looking at the Addon documentation <https://github.com/hassio-addons/addon-grafana/blob/main/grafana/DOCS.md#option-plugins>
