### ISSUE TITLE
❇ Mycroft AI

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/repository#66]
Request https://geekedoutsolutions.com/using-home-assistant-with-mycroft-ai-for-home-automation

<blockquote><img src="https://geekedoutsolutions.com/wp-content/uploads/2018/05/mycroft_featured.png" width="48" align="right"><div><img src="https://geekedoutsolutions.com/wp-content/uploads/2018/05/service_logo.png" height="14"> Geeked Out Solutions</div><div><strong><a href="https://geekedoutsolutions.com/using-home-assistant-with-mycroft-ai-for-home-automation">Using Home Assistant with Mycroft AI For Home Automation - Geeked Out Solutions</a></strong></div><div>Facebook Twitter LinkedIn</div></blockquote>

**Comment by s00500** [comment]
I guess Mic and Speaker setup should pretty much work similar to how it is done on the SnipsAI Addon
