### ISSUE TITLE
❇ Traefik

### ISSUE THREAD

**Issue by damylen** [hassio-addons/repository#67]
# Problem/Motivation

Traefik is a reverse proxy that plays well with docker and other integrations like 'let's encrypt'. It will make sure that all other integrations have easy to remember local (or public) urls, so we don't have to remember these port numbers.

https://traefik.io/

<blockquote><div><strong><a href="https://traefik.io/">Træfik</a></strong></div></blockquote>

**Comment by gerard33** [comment]
Would love to see a addon for Traefik as well.

**Comment by MrRaph** [comment]
Hi there,

I made an add-on for HassIO that runs Traefik.
It works on my setup but should still be considered as "work in progress" :)

Here it is : https://github.com/MrRaph/hassio-addons/tree/master/traefik-proxy

Have fun :)

**Comment by frenck** [comment]
There is an alternative add-on out.
Furthermore, we already have a reverse proxy in our catalog. I want to avoid making multiple of the same add-ons.

Thanks for suggesting it!
