### ISSUE TITLE
Nextcloud AIO (all-in-one) Addon

### ISSUE THREAD

**Issue by TheSpaceGod** [hassio-addons/repository#676]
# Problem/Motivation

There are a few docker images I plan on turning into HA addons in the near future, this being one of them. I would love to help and add this image to the community!

Project URL: https://github.com/nextcloud/all-in-one

## Expected behavior

N/A

## Actual behavior

N/A

## Steps to reproduce

N/A

## Proposed changes

N/A

**Comment by frenck** [comment]
Thanks for the issue; however, we are currently not accepting new add-ons to this repository. Of course, you can always publish your own.

../Frenck
