### ISSUE TITLE
Ollama Addon

### ISSUE THREAD

**Issue by TheSpaceGod** [hassio-addons/repository#677]
# Problem/Motivation

There are a few docker images I plan on turning into HA addons in the near future, this being one of them. I would love to help and add this image to the community!

Project URL: https://github.com/ollama/ollama
My current work: https://github.com/TheSpaceGod/hass-ollama-addon

## Expected behavior

N/A

## Actual behavior

N/A

## Steps to reproduce

N/A

## Proposed changes

N/A

**Comment by TheSpaceGod** [comment]
Also monitoring Ollama issue tickets to add support for iGPU usage for folks like me that will be running Ollama off of Intel NUC style hardware and using HAOS as their main server OS.

**Comment by TheSpaceGod** [comment]
This PR seems to be the best candidate for adding Ollama GPU support for most low/mid tier HAOS + Ollama setups: https://github.com/ollama/ollama/pull/5059

**Comment by sinclairpaul** [comment]
I would suggest checking the docs - https://github.com/hassio-addons/repository?tab=readme-ov-file#adding-a-new-add-on

**Comment by TheSpaceGod** [comment]
> I would suggest checking the docs - https://github.com/hassio-addons/repository?tab=readme-ov-file#adding-a-new-add-on

Woops! I was reading the documentation website for contributing guidance: 
"When contributing to our add-ons, please first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change." (https://addons.community/contributing/)

**Comment by frenck** [comment]
Thanks for the issue; however, we are currently not accepting new add-ons to this repository. Of course, you can always publish your own.

../Frenck
