### ISSUE TITLE
Open WebUI Addon

### ISSUE THREAD

**Issue by TheSpaceGod** [hassio-addons/repository#678]
There are a few docker images I plan on turning into HA addons in the near future, this being one of them. I would love to help and add this image to the community!

Project URL: https://github.com/open-webui/open-webui

## Expected behavior

N/A

## Actual behavior

N/A

## Steps to reproduce

N/A

## Proposed changes

N/A

**Comment by TheSpaceGod** [comment]
This issue will most likely relate to this purposed Ollama addon (https://github.com/hassio-addons/repository/issues/677) as a frontend GUI.

**Comment by frenck** [comment]
Thanks for the issue; however, we are currently not accepting new add-ons to this repository. Of course, you can always publish your own.

../Frenck
