### ISSUE TITLE
Homebridge not starting when using SSL/HTTPS in Home Assistant

### ISSUE THREAD

**Issue by mauriciobonani** [hassio-addons/repository#7]
I'm running HassIO on a Raspberry Pi 3 and after setting up SSL/HTTPS in HA Homebridge cannot start.

I don't know if I'm missing something in the settings but everything looks fine to me.

Please find attached the configuration files and a complete log.

[config.json.txt](https://github.com/hassio-addons/repository/files/1229258/config.json.txt)
[configuration.yaml.txt](https://github.com/hassio-addons/repository/files/1229260/configuration.yaml.txt)
[homebridge.log.txt](https://github.com/hassio-addons/repository/files/1229259/homebridge.log.txt)

**Comment by frenck** [comment]
Hi @mauriciobonani, I'm sorry to hear that you are experiencing issues with the add-on.

Have you tried changing the `host` configuration option to contain the URL you use yourself to connect to your Home Assistant frontend?

**Comment by mauriciobonani** [comment]
The host configuration option contained the IP address from docker0, after changing  to the IP address from eth0 everything seems to be working fine.

Thanks.
