### ISSUE TITLE
❇ GitLab Runner

### ISSUE THREAD

**Issue by timmo001** [hassio-addons/repository#70]
# Motivation

The ability to be able to create a GitLab Runner on a RPI or Vagrant HASS.io system for testing projects on an ARM/64 system

## Refs

https://docs.gitlab.com/runner/

<blockquote><div><strong><a href="https://docs.gitlab.com/runner/">GitLab Runner | GitLab</a></strong></div><div>Documentation for GitLab Community Edition, GitLab Enterprise Edition, Omnibus GitLab, and GitLab Runner.</div></blockquote>

**Comment by frenck** [comment]
Still not available widely for aarch64.

Furthermore, I'll be moving away from GitLab myself as well, hence I do no plan on creating an add-on for it.
