### ISSUE TITLE
Open web UI on appdaemon breaks when accessing remotely

### ISSUE THREAD

**Issue by Ten0** [hassio-addons/repository#700]
# Problem/Motivation

Clicking "Open WEB UI" when connected remotely does not work: it tries to open `http://<my-url>:5050/` but when connected remotely (DDNS and exposed HA on HTTPS), I don't necessarily have that NAT-ed.
In fact, I don't want to NAT this, because there's no authentication on there so it clearly can't be opened to outside.

There is demand for this to work: https://community.home-assistant.io/t/solved-unable-to-connect-to-web-ui/134193/6

## Proposed changes

My understanding is that HomeAssistant has a feature called "Ingress" that enables exposing the web UI as an iframe within Home Assistant:
- https://github.com/hassio-addons/addon-ssh/blob/d7c4c89b3c5f9c5948dae022041b006424e57250/ssh/config.yaml#L9-L11
- https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/

Then one should bind to the ingress port instead of to a fully exposed port, and it would:
1. work
2. be more secure (because it would now be authenticated by HomeAssistant instead of being exposed without authentication on the local network)

**Comment by frenck** [comment]
This app cannot work via Ingress.

If you want to expose it to the outside world, you'd have to do that yourself.

../Frenck

**Comment by Ten0** [comment]
Thanks for your answer. Would you have a second to elaborate on why it can't work via ingress, for future reference? Thanks.

**Comment by sinclairpaul** [comment]
The application needs to support being served from a path, i.e. /somefolder/mypath.  This can be a challenge for apps which assume everything is served from root.

**Comment by Ten0** [comment]
Thanks!
