### ISSUE TITLE
❇ NTP Server

### ISSUE THREAD

**Issue by ascillato** [hassio-addons/repository#73]
# Problem/Motivation

It is vey handy to have a Time Server in your local network so, your IoT devices can sync with it.
This is supported by default in Raspbian but not in Hassio.

## Expected behavior

Have a NTP Server to Sync

## Actual behavior

Hassio does not have NTP Server Support

## Proposed changes

There is already a Hassio Addon that can be included in your repository at:

https://github.com/ascillato/hass-io-addons

Original Author of the python NTP Server: https://github.com/limifly/ntpserver

## Example of use

If you have a Tasmota Device, it needs to sync with a NTP Server so its timers and other functions can work. So, if you set in Tasmota the command `ntpserver1 [hassio IP or hassio address]`, It will use Hassio as time source.

<blockquote><img src="https://avatars0.githubusercontent.com/u/35405447?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ascillato/hass-io-addons">ascillato/hass-io-addons</a></strong></div><div>hass-io-addons - Add Ons for HASSIO</div></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/3623909?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/limifly/ntpserver">limifly/ntpserver</a></strong></div><div>ntpserver - A Python based ntp server</div></blockquote>

**Comment by frenck** [comment]
Thank you for this suggestion @ascillato! I do like this idea :)

**Comment by frenck** [comment]
@ascillato, The community Project is an opensource project.
If you'd like to contribute or create an add-on for the project, feel free to do so 👍

**Comment by ascillato** [comment]
Ok, great!

Done.

I did the NTP Add-On for HASSIO at https://github.com/ascillato/hass-io-addons/tree/master/ntpserver

How we can add it to the community?

**Comment by frenck** [comment]
LOL @ascillato, that was quick (and backdated 😉 ).

Nevertheless, the community add-ons are build in a specific way.
For example:
- We use our own build base images
- We following some coding strict standards
- We provide (standarized) docs
- Are build upon the S6 init.

Feel free to check some of our add-ons out (including the CI) to get inspiration.

**Comment by frenck** [comment]
PS: Why use a Python script? Instead of the actual `ntpd`?

**Comment by ascillato** [comment]
I could not find any way of using the `ntpd` in hassio.

Besides, this pyhton implementation is very light and it is the one I'm using at home in my hassio as an add-on, for syncronizing time in all my devices.

Please, guide me in anything else needed to include NTP Server in the community add-ons

**Comment by frenck** [comment]
Python is kinda fat... will add 25~50 megs to a Docker container...

**Comment by ascillato** [comment]
The main objective of this, is having a NTP Server to retrieve time for home automation devices (like [Sonoff-Tasmota](https://github.com/arendst/Sonoff-Tasmota)) but in a local network without the need to connect to Internet.

If you use **Hassbian** or **Home Assistant manually installed** in a linux or raspbian, you will have a NTP Server by default installed there. But using Hass.io, you don't have that due to ResinOs does not have a NTP Server active.

That's why the actual proposed for this add-on

**Comment by frenck** [comment]
I think installing OpenNTPd inside an Alpine Docker container would do the trick.
We'd probably need some extra capabilities (I guess SYS_TIME is needed). Not sure if all are available in Hass.io, but a pull request for creating those is quickly done.

**Comment by ascillato** [comment]
Tested the new HassOs system and the NTP Server is still missing. So an ADD-ON for having a NTP Server for IoT Devices in Lan is needed.

**Comment by GaryOkie** [comment]
+1 for having an official **NTPD** HASSIO Add-on or included in the build by default or enabled via some other config option.

@frenck said 

> I think installing OpenNTPd inside an Alpine Docker container would do the trick.

Is there a PR in progress to make this happen?

All my Chinese-made IP cameras are blocked from Internet access, including NTP via WAN, and I'm tired of manually adjusting the time on them.

I'll look at using @ascillato 's custom add-on for now.   Thanks.

**Comment by frenck** [comment]
Released: https://github.com/hassio-addons/addon-chrony

**Comment by ascillato** [comment]
Great news! Thanks

**Comment by GaryOkie** [comment]
Perfect Timing!     (pun intended)

Thanks!
