### ISSUE TITLE
❇ sqlite-web

### ISSUE THREAD

**Issue by robmarkcole** [hassio-addons/repository#74]
# Problem/Motivation
I want to browse the HA sqlite database quickly and perhaps export data to csv, but there's no nice tool to do this from the HA front-end. This tool provides that functionality and is suitable for less techncial HA users https://github.com/coleifer/sqlite-web

<blockquote><img src="https://avatars0.githubusercontent.com/u/119974?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/coleifer/sqlite-web">coleifer/sqlite-web</a></strong></div><div>sqlite-web - Web-based SQLite database browser written in Python</div></blockquote>

**Comment by adamotte** [comment]
Vote up !

**Comment by robmarkcole** [comment]
Added by @ludeeus
