### ISSUE TITLE
DietPi

### ISSUE THREAD

**Issue by adamotte** [hassio-addons/repository#86]
I love [DietPi](https://dietpi.com/) and it would be great if i can monitor versions and updates or backup. 

DietPi offer scripts for each : 
- [dietpi-update](https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-update)
- [dietpi-backup](https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-backup)

We can easily do that manually in configuration but an addon is more user-friendly.

**Comment by frenck** [comment]
This use case would have a very small user base and can be done with the "SSH & Web Terminal" add-on already.
I don't see a big value for the community for this add-on, which takes time to develop and maintain. Therefore have to decline it.

PS: The update script could be transformed into an actual Home Assitant component.
