### ISSUE TITLE
❇ Glances

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#87]
# Motivation

Glances has been requested many times, via Twitter and Discord.

# Ref

https://nicolargo.github.io/glances/
https://github.com/nicolargo/glances/tree/develop/docker-files

<blockquote><div><strong><a href="https://nicolargo.github.io/glances/">Glances - An Eye on your system</a></strong></div><div>Glances is a cross-platform curses-based system monitoring tool written in Python.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/776747?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/nicolargo/glances">nicolargo/glances</a></strong></div><div>Glances an Eye on your system. A top/htop alternative. - nicolargo/glances</div></blockquote>

**Comment by frenck** [comment]
This add-on is 95% done, but is currently blocked by:

home-assistant/home-assistant-polymer#1710

**Comment by DavidDeSloovere** [comment]
@frenck looks like that blocking issue is closed, will we see yet another great hassio addon coming from frenck's addon factory? 😁

**Comment by frenck** [comment]
@DavidDeSloovere Is indeed is no longer blocked. The add-on has been finished and is currently in testing.

**Comment by frenck** [comment]
Released in https://github.com/hassio-addons/addon-glances
