### ISSUE TITLE
❇ Muximux

### ISSUE THREAD

**Issue by frenck** [hassio-addons/repository#89]
# Motivation

This is a lightweight portal to view & manage your webapps without having to run anything more than a PHP enabled webserver. With Muximux you don't need to keep multiple tabs open, or bookmark the URL to all of your apps.

# Ref

https://github.com/mescon/Muximux

<blockquote><img src="https://avatars0.githubusercontent.com/u/5875228?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/mescon/Muximux">mescon/Muximux</a></strong></div><div>A lightweight way to manage your HTPC. Contribute to mescon/Muximux development by creating an account on GitHub.</div></blockquote>

**Comment by Antoni-K** [comment]
I'm going to work on this

**Comment by sinclairpaul** [comment]
Project seems a bit dead and there a few alternatives, close it out?

**Comment by frenck** [comment]
@sinclairpaul Agreed.
