### ISSUE TITLE
❇Virtual Google Home Assistant

### ISSUE THREAD

**Issue by ArnoutVerbeken** [hassio-addons/repository#91]
# Problem/Motivation

As requested by Frenck, I am opening this ticket to have a new addon that has the functionality of a Google Home Assistant.
The existing addon on 
https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music  
is broken and not maintained anymore.
The SDK can be found on https://developers.google.com/assistant/sdk

Somebody was able to create something "new" in a non-hassio environment, but he does not have the skills to create an addon for it (and neither have I - still learning).
More info about this "new way" can be found on
https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274/234

I think creating an addon of that one is a good start.  But I think it is still not using the full potential of the SDK and API's mentionned above.
But I will let that decision over to the experts.

## Expected behavior

My personal use case for this is to broadcast messages on my personal Google Home devices.  Right now, this is done by google_tts, but it uses a more static voice than the new SDK/API.

## Actual behavior

An existing addon seems to stop working and seems to be not maintained anymore

## Steps to reproduce

Install/configure the addon from https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music and notice it is not working anymore.
You will still see the "broadcast" messages in your Google History, but they are never played on the devices itself.

## Proposed changes

Create a new addon, based on https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274/234

<blockquote><img src="https://assets-cdn.github.com/favicon.ico" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274">Community Hass.io Add-on: Google Assistant Webserver (broadcast messages without interrupting music)</a></strong></div><div>Hello everyone!  Just recently, I was able to successfully get my add-on for the text-based Google Assistant working on Hass.io.  Here is the add-on repo:     Once installed, the setup is similar to https://home-assistant.io/addons/google_assistant/  So, it needs the google_assistant.json file added to /share  Also, it follows the same OAuth setup.  Once completely running and set up, you can broadcast a text message to your Google Home devices using:  http://hassio.local:5000/broadcast_message?...</div></blockquote>
<blockquote><img src="https://developers.google.com/_static/ff3e28d40c/images/share/devsite-indigo.png" width="48" align="right"><div>Google Developers</div><div><strong><a href="https://developers.google.com/assistant/sdk/">Google Assistant SDK  |  Google Assistant SDK for devices
       |  Google Developers</a></strong></div><div>The Google Assistant SDK for devices lets you embed the Google Assistant in your devices.
</div></blockquote>
<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/chocomega/200/13825_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274/234">Community Hass.io Add-on: Google Assistant Webserver (broadcast messages without interrupting music)</a></strong></div><div>For those who meet the requirements of the Google Assistant Library (i.e. arch linux-armv7l or linux-x86_64, audio capture and playback), feel free to try this workaround:  Disclaimer: this is not an Hassio add-on and I don’t intend to create one as I don’t use Hassio myself.  The following Python script is provided “as is”. With some linux knowledge this script can be run as a system daemon.    You will need first to follow this guide “Embed the Google Assistant”:  https://developers.google.com...</div></blockquote>
<blockquote><img src="https://assets-cdn.github.com/favicon.ico" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274">Community Hass.io Add-on: Google Assistant Webserver (broadcast messages without interrupting music)</a></strong></div><div>Hello everyone!  Just recently, I was able to successfully get my add-on for the text-based Google Assistant working on Hass.io.  Here is the add-on repo:     Once installed, the setup is similar to https://home-assistant.io/addons/google_assistant/  So, it needs the google_assistant.json file added to /share  Also, it follows the same OAuth setup.  Once completely running and set up, you can broadcast a text message to your Google Home devices using:  http://hassio.local:5000/broadcast_message?...</div></blockquote>
<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/chocomega/200/13825_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274/234">Community Hass.io Add-on: Google Assistant Webserver (broadcast messages without interrupting music)</a></strong></div><div>For those who meet the requirements of the Google Assistant Library (i.e. arch linux-armv7l or linux-x86_64, audio capture and playback), feel free to try this workaround:  Disclaimer: this is not an Hassio add-on and I don’t intend to create one as I don’t use Hassio myself.  The following Python script is provided “as is”. With some linux knowledge this script can be run as a system daemon.    You will need first to follow this guide “Embed the Google Assistant”:  https://developers.google.com...</div></blockquote>

**Comment by frenck** [comment]
Thanks for opening this @ArnoutVerbeken, will check it out!

**Comment by ArnoutVerbeken** [comment]
This can be of interest too:
https://github.com/greghesp/assistant-relay/blob/master/readMe.md

**Comment by ArnoutVerbeken** [comment]
Found this also.
https://github.com/shivasiddharth/GassistPi

**Comment by ArnoutVerbeken** [comment]
Think this is it.  Just need to dockerize it.
https://community.smartthings.com/t/release-google-assistant-relay-v2-0-google-home-audio-notifications/136473

**Comment by capstan1** [comment]
Any news on this?

**Comment by frenck** [comment]
@capstan1 Still just marked as an idea.

**Comment by capstan1** [comment]
This might be of interest, too:
https://community.home-assistant.io/t/google-assistant-webserver-in-a-docker-container/88820

**Comment by marcelveldt** [comment]
This what you mean ?
https://github.com/marcelveldt/hassio-addons-repo/tree/master/google-assistant-webserver

I can extend/polish it a bit and submit to the community repo, no problem.

**Comment by frenck** [comment]
Thanks @marcelveldt, however, the add-on you listed does not need a bit of polish to match the community add-ons, but almost a rewrite.

Secondly, I've stopped accepting add-ons from others.

**Comment by marcelveldt** [comment]
Hi Frenck, Yeah, I had a rewrite in mink. This one is based on that original version but it is no rocket science to make it a descent solution. Let me know if you're interested. Otherwise I'll just keep it  on my own repo.
