### ISSUE TITLE
❇ Emoncms

### ISSUE THREAD

**Issue by codedmind** [hassio-addons/repository#92]
# Problem/Motivation

Have emoncms as homeassistant addon, that will work with mariadb

**Comment by james-fry** [comment]
+1 for this addon

**Comment by sperglord8008s** [comment]
does seam very wastefully having 2 Rpi to do the work of 1!!

**Comment by inverse** [comment]
Can try and work on this  - I don't actively use it but seemed like a good learning opportunity. 

https://github.com/inverse/hassio-addon-emoncms/pull/1

It's based of Frenck's TasmotaAdmin :)

**Comment by frenck** [comment]
Thanks, closing it here.
